// Sample recipe data
const existingRecipes = [
  {
    title: 'Quinoa Buddha Bowl',
    description: 'A nourishing bowl packed with protein-rich quinoa, roasted vegetables, and tahini dressing.',
    cookingTime: 30,
    servings: 2,
    difficulty: 'EASY',
    cuisineType: 'international',
    regionOfOrigin: 'Global',
    imageUrl: '/images/recipes/quinoa-buddha-bowl.jpg',
    calories: 450,
    type: 'LUNCH',
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    isDairyFree: true,
    isNutFree: false,
    ingredients: [
      { name: 'Quinoa', amount: 1, unit: 'cup' },
      { name: 'Sweet Potato', amount: 1, unit: 'medium', notes: 'cubed' },
      { name: 'Chickpeas', amount: 1, unit: 'can', notes: 'drained and rinsed' },
      { name: 'Kale', amount: 2, unit: 'cups', notes: 'chopped' },
      { name: 'Tahini', amount: 2, unit: 'tablespoons' },
    ],
    instructions: [
      { stepNumber: 1, description: 'Cook quinoa according to package instructions.' },
      { stepNumber: 2, description: 'Roast sweet potato cubes at 400°F for 20 minutes.' },
      { stepNumber: 3, description: 'Massage kale with olive oil and season.' },
      { stepNumber: 4, description: 'Assemble bowls and drizzle with tahini dressing.' },
    ],
    nutritionFacts: {
      protein: 15,
      carbs: 65,
      fat: 12,
      fiber: 8,
      sugar: 6,
      sodium: 400,
    },
  },
  {
    title: 'Japanese Miso Soup',
    description: 'Traditional Japanese breakfast soup with tofu, wakame, and green onions.',
    cookingTime: 15,
    servings: 2,
    difficulty: 'EASY',
    cuisineType: 'japanese',
    regionOfOrigin: 'Japan',
    imageUrl: '/images/recipes/japanese-miso-soup.jpg',
    calories: 120,
    type: 'BREAKFAST',
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    isDairyFree: true,
    isNutFree: true,
    ingredients: [
      { name: 'Dashi Stock', amount: 4, unit: 'cups' },
      { name: 'Miso Paste', amount: 3, unit: 'tablespoons' },
      { name: 'Tofu', amount: 200, unit: 'grams', notes: 'cubed' },
      { name: 'Wakame Seaweed', amount: 2, unit: 'tablespoons', notes: 'dried' },
      { name: 'Green Onions', amount: 2, unit: 'stalks', notes: 'chopped' },
    ],
    instructions: [
      { stepNumber: 1, description: 'Bring dashi stock to a simmer.' },
      { stepNumber: 2, description: 'Dissolve miso paste in a small amount of hot stock.' },
      { stepNumber: 3, description: 'Add tofu and wakame to the stock.' },
      { stepNumber: 4, description: 'Stir in miso mixture and garnish with green onions.' },
    ],
    nutritionFacts: {
      protein: 8,
      carbs: 12,
      fat: 4,
      fiber: 2,
      sugar: 1,
      sodium: 800,
    },
  },
  {
    title: 'Mediterranean Grilled Chicken',
    description: 'Herb-marinated chicken with Greek salad and tzatziki sauce.',
    cookingTime: 45,
    servings: 4,
    difficulty: 'MEDIUM',
    cuisineType: 'mediterranean',
    regionOfOrigin: 'Greece',
    imageUrl: '/images/recipes/mediterranean-grilled-chicken.jpg',
    calories: 420,
    type: 'DINNER',
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: true,
    isDairyFree: false,
    isNutFree: true,
    ingredients: [
      { name: 'Chicken Breasts', amount: 4, unit: 'pieces' },
      { name: 'Greek Yogurt', amount: 1, unit: 'cup' },
      { name: 'Lemon', amount: 2, unit: 'whole' },
      { name: 'Garlic', amount: 4, unit: 'cloves' },
      { name: 'Oregano', amount: 2, unit: 'tablespoons' },
    ],
    instructions: [
      { stepNumber: 1, description: 'Marinate chicken in yogurt, lemon, garlic, and herbs.' },
      { stepNumber: 2, description: 'Grill chicken until cooked through.' },
      { stepNumber: 3, description: 'Prepare Greek salad and tzatziki sauce.' },
      { stepNumber: 4, description: 'Serve chicken with salad and sauce.' },
    ],
    nutritionFacts: {
      protein: 35,
      carbs: 12,
      fat: 28,
      fiber: 3,
      sugar: 4,
      sodium: 520,
    },
  },
  {
    title: 'Vegan Chocolate Energy Balls',
    description: 'No-bake energy balls made with dates, nuts, and cocoa.',
    cookingTime: 20,
    servings: 12,
    difficulty: 'EASY',
    cuisineType: 'international',
    regionOfOrigin: 'Global',
    imageUrl: '/images/recipes/vegan-chocolate-energy-balls.jpg',
    calories: 120,
    type: 'SNACK',
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    isDairyFree: true,
    isNutFree: false,
    ingredients: [
      { name: 'Medjool Dates', amount: 1, unit: 'cup', notes: 'pitted' },
      { name: 'Almonds', amount: 1, unit: 'cup' },
      { name: 'Cocoa Powder', amount: 2, unit: 'tablespoons' },
      { name: 'Chia Seeds', amount: 1, unit: 'tablespoon' },
      { name: 'Vanilla Extract', amount: 1, unit: 'teaspoon' },
    ],
    instructions: [
      { stepNumber: 1, description: 'Process dates and almonds in a food processor.' },
      { stepNumber: 2, description: 'Add cocoa powder, chia seeds, and vanilla.' },
      { stepNumber: 3, description: 'Roll mixture into balls.' },
      { stepNumber: 4, description: 'Refrigerate for 30 minutes before serving.' },
    ],
    nutritionFacts: {
      protein: 3,
      carbs: 18,
      fat: 7,
      fiber: 3,
      sugar: 12,
      sodium: 2,
    },
  },
  {
    title: 'Keto Cauliflower Mac and Cheese',
    description: 'Low-carb version of the classic comfort food using cauliflower.',
    cookingTime: 35,
    servings: 6,
    difficulty: 'MEDIUM',
    cuisineType: 'american',
    regionOfOrigin: 'United States',
    imageUrl: '/images/recipes/keto-cauliflower-mac-and-cheese.jpg',
    calories: 350,
    type: 'DINNER',
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: true,
    isDairyFree: false,
    isNutFree: true,
    ingredients: [
      { name: 'Cauliflower', amount: 2, unit: 'heads', notes: 'cut into florets' },
      { name: 'Heavy Cream', amount: 1, unit: 'cup' },
      { name: 'Cheddar Cheese', amount: 2, unit: 'cups', notes: 'shredded' },
      { name: 'Cream Cheese', amount: 4, unit: 'ounces' },
      { name: 'Garlic Powder', amount: 1, unit: 'teaspoon' },
    ],
    instructions: [
      { stepNumber: 1, description: 'Steam cauliflower until tender.' },
      { stepNumber: 2, description: 'Make cheese sauce with cream, cheeses, and seasonings.' },
      { stepNumber: 3, description: 'Combine cauliflower with cheese sauce.' },
      { stepNumber: 4, description: 'Bake until bubbly and golden.' },
    ],
    nutritionFacts: {
      protein: 18,
      carbs: 8,
      fat: 28,
      fiber: 3,
      sugar: 2,
      sodium: 480,
    },
  },
  {
    title: 'Spicy Pad Thai',
    description: 'Classic Thai stir-fried rice noodles with tofu, shrimp, and peanuts in a tangy-sweet sauce.',
    cookingTime: 30,
    servings: 4,
    difficulty: 'MEDIUM',
    cuisineType: 'thai',
    regionOfOrigin: 'Thailand',
    imageUrl: '/images/recipes/spicy-pad-thai.jpg',
    calories: 450,
    type: 'DINNER',
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: true,
    isDairyFree: true,
    isNutFree: false,
    ingredients: [
      { name: 'Rice Noodles', amount: 8, unit: 'ounces' },
      { name: 'Tofu', amount: 8, unit: 'ounces', notes: 'firm, cubed' },
      { name: 'Shrimp', amount: 8, unit: 'ounces', notes: 'peeled and deveined' },
      { name: 'Bean Sprouts', amount: 2, unit: 'cups' },
      { name: 'Peanuts', amount: 0.5, unit: 'cup', notes: 'crushed' },
    ],
    instructions: [
      { stepNumber: 1, description: 'Soak rice noodles in warm water until soft.' },
      { stepNumber: 2, description: 'Stir-fry tofu and shrimp until cooked.' },
      { stepNumber: 3, description: 'Add noodles and sauce, toss until well-combined.' },
      { stepNumber: 4, description: 'Add bean sprouts and crushed peanuts.' },
    ],
    nutritionFacts: {
      protein: 25,
      carbs: 58,
      fat: 15,
      fiber: 4,
      sugar: 8,
      sodium: 850,
    },
  },
  {
    title: 'Butter Chicken',
    description: 'Creamy, aromatic Indian curry with tender chicken pieces in a rich tomato-based sauce.',
    cookingTime: 45,
    servings: 6,
    difficulty: 'MEDIUM',
    cuisineType: 'indian',
    regionOfOrigin: 'India',
    imageUrl: '/images/recipes/butter-chicken.jpg',
    calories: 550,
    type: 'DINNER',
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: true,
    isDairyFree: false,
    isNutFree: true,
    ingredients: [
      { name: 'Chicken Thighs', amount: 2, unit: 'pounds', notes: 'boneless' },
      { name: 'Yogurt', amount: 1, unit: 'cup' },
      { name: 'Tomato Sauce', amount: 2, unit: 'cups' },
      { name: 'Heavy Cream', amount: 1, unit: 'cup' },
      { name: 'Garam Masala', amount: 2, unit: 'tablespoons' },
    ],
    instructions: [
      { stepNumber: 1, description: 'Marinate chicken in yogurt and spices.' },
      { stepNumber: 2, description: 'Cook chicken until golden brown.' },
      { stepNumber: 3, description: 'Simmer in tomato sauce until tender.' },
      { stepNumber: 4, description: 'Finish with cream and garnish.' },
    ],
    nutritionFacts: {
      protein: 32,
      carbs: 12,
      fat: 38,
      fiber: 2,
      sugar: 6,
      sodium: 720,
    },
  },
  {
    title: 'Sushi Roll Platter',
    description: 'Assorted fresh sushi rolls including California, Spicy Tuna, and Vegetable rolls.',
    cookingTime: 60,
    servings: 4,
    difficulty: 'HARD',
    cuisineType: 'japanese',
    regionOfOrigin: 'Japan',
    imageUrl: '/images/recipes/sushi-roll-platter.jpg',
    calories: 400,
    type: 'DINNER',
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: false,
    isDairyFree: true,
    isNutFree: true,
    ingredients: [
      { name: 'Sushi Rice', amount: 2, unit: 'cups' },
      { name: 'Nori Sheets', amount: 6, unit: 'sheets' },
      { name: 'Tuna', amount: 8, unit: 'ounces', notes: 'sashimi grade' },
      { name: 'Cucumber', amount: 1, unit: 'whole' },
      { name: 'Avocado', amount: 2, unit: 'whole' },
    ],
    instructions: [
      { stepNumber: 1, description: 'Cook and season sushi rice.' },
      { stepNumber: 2, description: 'Prepare fillings and cut into strips.' },
      { stepNumber: 3, description: 'Roll sushi using bamboo mat.' },
      { stepNumber: 4, description: 'Slice rolls and arrange on platter.' },
    ],
    nutritionFacts: {
      protein: 18,
      carbs: 45,
      fat: 12,
      fiber: 4,
      sugar: 2,
      sodium: 380,
    },
  },
  {
    title: 'Vegetable Stir-Fry',
    description: 'Colorful mix of fresh vegetables in a savory sauce with tofu.',
    cookingTime: 25,
    servings: 4,
    difficulty: 'EASY',
    cuisineType: 'chinese',
    regionOfOrigin: 'China',
    imageUrl: '/images/recipes/vegetable-stir-fry.jpg',
    calories: 300,
    type: 'DINNER',
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    isDairyFree: true,
    isNutFree: true,
    ingredients: [
      { name: 'Mixed Vegetables', amount: 6, unit: 'cups' },
      { name: 'Tofu', amount: 14, unit: 'ounces', notes: 'firm' },
      { name: 'Soy Sauce', amount: 3, unit: 'tablespoons' },
      { name: 'Ginger', amount: 1, unit: 'tablespoon', notes: 'minced' },
      { name: 'Garlic', amount: 3, unit: 'cloves', notes: 'minced' },
    ],
    instructions: [
      { stepNumber: 1, description: 'Press and cube tofu.' },
      { stepNumber: 2, description: 'Stir-fry vegetables until crisp-tender.' },
      { stepNumber: 3, description: 'Add tofu and sauce.' },
      { stepNumber: 4, description: 'Cook until heated through.' },
    ],
    nutritionFacts: {
      protein: 15,
      carbs: 25,
      fat: 12,
      fiber: 6,
      sugar: 8,
      sodium: 600,
    },
  },
  {
    title: 'Horiatiki (Greek Salad)',
    description: 'Fresh Mediterranean salad with tomatoes, cucumbers, olives, and feta cheese.',
    cookingTime: 15,
    servings: 4,
    difficulty: 'EASY',
    cuisineType: 'mediterranean',
    regionOfOrigin: 'Greece',
    imageUrl: '/images/recipes/horiatiki-greek-salad.jpg',
    calories: 250,
    type: 'LUNCH',
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: true,
    isDairyFree: false,
    isNutFree: true,
    ingredients: [
      { name: 'Tomatoes', amount: 4, unit: 'whole' },
      { name: 'Cucumber', amount: 1, unit: 'large' },
      { name: 'Red Onion', amount: 1, unit: 'medium' },
      { name: 'Feta Cheese', amount: 200, unit: 'grams' },
      { name: 'Kalamata Olives', amount: 1, unit: 'cup' },
    ],
    instructions: [
      { stepNumber: 1, description: 'Chop vegetables into chunks.' },
      { stepNumber: 2, description: 'Combine in a large bowl.' },
      { stepNumber: 3, description: 'Add feta and olives.' },
      { stepNumber: 4, description: 'Dress with olive oil and oregano.' },
    ],
    nutritionFacts: {
      protein: 8,
      carbs: 12,
      fat: 20,
      fiber: 4,
      sugar: 6,
      sodium: 580,
    },
  },
  {
    title: 'Traditional French Croissants',
    description: 'Flaky, buttery French pastries made from laminated dough.',
    cookingTime: 180,
    servings: 8,
    difficulty: 'HARD',
    cuisineType: 'french',
    regionOfOrigin: 'France',
    imageUrl: '/images/recipes/traditional-french-croissants.jpg',
    calories: 280,
    type: 'BREAKFAST',
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: false,
    isDairyFree: false,
    isNutFree: true,
    ingredients: [
      { name: 'All-Purpose Flour', amount: 4, unit: 'cups' },
      { name: 'Butter', amount: 1.5, unit: 'cups', notes: 'cold, for laminating' },
      { name: 'Active Dry Yeast', amount: 2.25, unit: 'teaspoons' },
      { name: 'Milk', amount: 1, unit: 'cup', notes: 'warm' },
      { name: 'Sugar', amount: 2, unit: 'tablespoons' },
    ],
    instructions: [
      { stepNumber: 1, description: 'Make enriched dough and chill.' },
      { stepNumber: 2, description: 'Laminate dough with butter through multiple folds.' },
      { stepNumber: 3, description: 'Shape croissants and proof.' },
      { stepNumber: 4, description: 'Bake until golden brown.' },
    ],
    nutritionFacts: {
      protein: 5,
      carbs: 28,
      fat: 18,
      fiber: 1,
      sugar: 3,
      sodium: 220,
    },
  },
  {
    title: 'Korean Bibimbap',
    description: 'A colorful rice bowl topped with vegetables, meat, and gochujang sauce.',
    cookingTime: 45,
    servings: 4,
    difficulty: 'MEDIUM',
    cuisineType: 'korean',
    regionOfOrigin: 'Korea',
    imageUrl: '/images/recipes/korean-bibimbap.jpg',
    calories: 480,
    type: 'LUNCH',
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: true,
    isDairyFree: true,
    isNutFree: true,
    ingredients: [
      { name: 'Rice', amount: 2, unit: 'cups' },
      { name: 'Ground Beef', amount: 0.5, unit: 'pound' },
      { name: 'Spinach', amount: 2, unit: 'cups' },
      { name: 'Carrots', amount: 2, unit: 'medium' },
      { name: 'Gochujang', amount: 3, unit: 'tablespoons' },
    ],
    instructions: [
      { stepNumber: 1, description: 'Cook rice and prepare vegetables.' },
      { stepNumber: 2, description: 'Season and cook ground beef.' },
      { stepNumber: 3, description: 'Arrange ingredients in bowls.' },
      { stepNumber: 4, description: 'Top with fried egg and gochujang sauce.' },
    ],
    nutritionFacts: {
      protein: 22,
      carbs: 65,
      fat: 16,
      fiber: 4,
      sugar: 3,
      sodium: 680,
    },
  },
  {
    title: 'Moroccan Tagine',
    description: 'A traditional North African stew of meat and vegetables, slow-cooked to perfection in a distinctive clay pot.',
    cookingTime: 120,
    servings: 6,
    difficulty: 'MEDIUM',
    cuisineType: 'moroccan',
    regionOfOrigin: 'Morocco',
    imageUrl: 'https://salimaskitchen.com/wp-content/uploads/2023/01/How-to-Make-Moroccan-Chicken-Tajine-Tagine-Salimas-Kitchen-17.jpg',
    calories: 380,
    type: 'DINNER',
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    isDairyFree: true,
    isNutFree: true,
    ingredients: [
      { name: 'Chickpeas', amount: 2, unit: 'cans' },
      { name: 'Sweet Potatoes', amount: 2, unit: 'large' },
      { name: 'Preserved Lemon', amount: 1, unit: 'whole' },
      { name: 'Green Olives', amount: 1, unit: 'cup' },
      { name: 'Ras el Hanout', amount: 2, unit: 'tablespoons' },
    ],
    instructions: [
      { stepNumber: 1, description: 'Layer vegetables in tagine.' },
      { stepNumber: 2, description: 'Add spices and preserved lemon.' },
      { stepNumber: 3, description: 'Slow cook until tender.' },
      { stepNumber: 4, description: 'Garnish with olives and herbs.' },
    ],
    nutritionFacts: {
      protein: 12,
      carbs: 45,
      fat: 14,
      fiber: 11,
      sugar: 8,
      sodium: 520,
    },
  },
  {
    title: 'Vietnamese Pho',
    description: 'Traditional Vietnamese noodle soup with aromatic broth and herbs.',
    cookingTime: 180,
    servings: 6,
    difficulty: 'HARD',
    cuisineType: 'vietnamese',
    regionOfOrigin: 'Vietnam',
    imageUrl: '/images/recipes/vietnamese-pho.jpg',
    calories: 320,
    type: 'LUNCH',
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: true,
    isDairyFree: true,
    isNutFree: true,
    ingredients: [
      { name: 'Beef Bones', amount: 5, unit: 'pounds', notes: 'for broth' },
      { name: 'Rice Noodles', amount: 1, unit: 'pound' },
      { name: 'Star Anise', amount: 3, unit: 'whole' },
      { name: 'Ginger', amount: 4, unit: 'inches' },
      { name: 'Bean Sprouts', amount: 2, unit: 'cups' },
    ],
    instructions: [
      { stepNumber: 1, description: 'Simmer bones and spices for broth.' },
      { stepNumber: 2, description: 'Prepare noodles and garnishes.' },
      { stepNumber: 3, description: 'Strain and season broth.' },
      { stepNumber: 4, description: 'Assemble bowls with noodles and toppings.' },
    ],
    nutritionFacts: {
      protein: 24,
      carbs: 42,
      fat: 8,
      fiber: 2,
      sugar: 3,
      sodium: 890,
    },
  },
  {
    title: 'Mexican Chilaquiles',
    description: 'Crispy tortilla chips simmered in salsa verde with eggs and cheese.',
    cookingTime: 30,
    servings: 4,
    difficulty: 'EASY',
    cuisineType: 'mexican',
    regionOfOrigin: 'Mexico',
    imageUrl: '/images/recipes/mexican-chilaquiles.jpg',
    calories: 420,
    type: 'BREAKFAST',
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: true,
    isDairyFree: false,
    isNutFree: true,
    ingredients: [
      { name: 'Corn Tortillas', amount: 12, unit: 'pieces' },
      { name: 'Salsa Verde', amount: 2, unit: 'cups' },
      { name: 'Eggs', amount: 4, unit: 'large' },
      { name: 'Queso Fresco', amount: 1, unit: 'cup' },
      { name: 'Cilantro', amount: 0.5, unit: 'cup' },
    ],
    instructions: [
      { stepNumber: 1, description: 'Cut and fry tortillas until crispy.' },
      { stepNumber: 2, description: 'Simmer chips in warm salsa verde.' },
      { stepNumber: 3, description: 'Top with fried eggs.' },
      { stepNumber: 4, description: 'Garnish with cheese and cilantro.' },
    ],
    nutritionFacts: {
      protein: 18,
      carbs: 48,
      fat: 22,
      fiber: 6,
      sugar: 4,
      sodium: 680,
    },
  },
  {
    title: 'Spanish Paella',
    description: 'Traditional Spanish rice dish with saffron, seafood, and vegetables.',
    cookingTime: 60,
    servings: 6,
    difficulty: 'HARD',
    cuisineType: 'spanish',
    regionOfOrigin: 'Spain',
    imageUrl: '/images/recipes/spanish-paella.jpg',
    calories: 550,
    type: 'DINNER',
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: true,
    isDairyFree: true,
    isNutFree: true,
    ingredients: [
      { name: 'Bomba Rice', amount: 2, unit: 'cups' },
      { name: 'Mixed Seafood', amount: 1, unit: 'pound' },
      { name: 'Saffron', amount: 1, unit: 'pinch' },
      { name: 'Bell Peppers', amount: 2, unit: 'whole' },
      { name: 'Tomatoes', amount: 2, unit: 'whole' },
    ],
    instructions: [
      { stepNumber: 1, description: 'Toast rice with saffron.' },
      { stepNumber: 2, description: 'Add vegetables and broth.' },
      { stepNumber: 3, description: 'Add seafood and cook until done.' },
      { stepNumber: 4, description: 'Create socarrat (crispy bottom).' },
    ],
    nutritionFacts: {
      protein: 28,
      carbs: 65,
      fat: 12,
      fiber: 4,
      sugar: 5,
      sodium: 720,
    },
  },
  {
    title: 'Vegan Ramen',
    description: 'Plant-based version of the classic Japanese noodle soup.',
    cookingTime: 90,
    servings: 4,
    difficulty: 'MEDIUM',
    cuisineType: 'japanese',
    regionOfOrigin: 'Japan',
    imageUrl: '/images/recipes/vegan-ramen.jpg',
    calories: 380,
    type: 'LUNCH',
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: false,
    isDairyFree: true,
    isNutFree: true,
    ingredients: [
      { name: 'Ramen Noodles', amount: 4, unit: 'portions' },
      { name: 'Mushrooms', amount: 8, unit: 'ounces' },
      { name: 'Kombu', amount: 2, unit: 'pieces' },
      { name: 'Miso Paste', amount: 4, unit: 'tablespoons' },
      { name: 'Corn', amount: 1, unit: 'cup' },
    ],
    instructions: [
      { stepNumber: 1, description: 'Make mushroom and kombu broth.' },
      { stepNumber: 2, description: 'Prepare toppings and noodles.' },
      { stepNumber: 3, description: 'Season broth with miso.' },
      { stepNumber: 4, description: 'Assemble bowls with noodles and toppings.' },
    ],
    nutritionFacts: {
      protein: 14,
      carbs: 68,
      fat: 6,
      fiber: 8,
      sugar: 4,
      sodium: 890,
    },
  },
  {
    title: 'Lebanese Fattoush',
    description: 'Middle Eastern bread salad with sumac and pomegranate molasses.',
    cookingTime: 20,
    servings: 4,
    difficulty: 'EASY',
    cuisineType: 'middle-eastern',
    regionOfOrigin: 'Lebanon',
    imageUrl: '/images/recipes/lebanese-fattoush.jpg',
    calories: 280,
    type: 'LUNCH',
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: false,
    isDairyFree: true,
    isNutFree: true,
    ingredients: [
      { name: 'Pita Bread', amount: 2, unit: 'pieces' },
      { name: 'Romaine Lettuce', amount: 1, unit: 'head' },
      { name: 'Sumac', amount: 2, unit: 'tablespoons' },
      { name: 'Pomegranate Molasses', amount: 2, unit: 'tablespoons' },
      { name: 'Mixed Herbs', amount: 1, unit: 'cup' },
    ],
    instructions: [
      { stepNumber: 1, description: 'Toast pita until crispy.' },
      { stepNumber: 2, description: 'Chop vegetables and herbs.' },
      { stepNumber: 3, description: 'Make sumac dressing.' },
      { stepNumber: 4, description: 'Toss all ingredients together.' },
    ],
    nutritionFacts: {
      protein: 6,
      carbs: 42,
      fat: 12,
      fiber: 6,
      sugar: 8,
      sodium: 380,
    },
  },
  {
    title: 'Brazilian Açaí Bowl',
    description: 'Refreshing breakfast bowl with açaí, fruits, and granola.',
    cookingTime: 15,
    servings: 2,
    difficulty: 'EASY',
    cuisineType: 'brazilian',
    regionOfOrigin: 'Brazil',
    imageUrl: '/images/recipes/brazilian-acai-bowl.jpg',
    calories: 320,
    type: 'BREAKFAST',
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    isDairyFree: true,
    isNutFree: false,
    ingredients: [
      { name: 'Açaí Puree', amount: 200, unit: 'grams' },
      { name: 'Banana', amount: 1, unit: 'whole' },
      { name: 'Mixed Berries', amount: 1, unit: 'cup' },
      { name: 'Granola', amount: 0.5, unit: 'cup' },
      { name: 'Honey', amount: 2, unit: 'tablespoons' },
    ],
    instructions: [
      { stepNumber: 1, description: 'Blend açaí with banana.' },
      { stepNumber: 2, description: 'Pour into bowls.' },
      { stepNumber: 3, description: 'Top with fresh fruits.' },
      { stepNumber: 4, description: 'Add granola and drizzle honey.' },
    ],
    nutritionFacts: {
      protein: 8,
      carbs: 52,
      fat: 14,
      fiber: 12,
      sugar: 28,
      sodium: 45,
    },
  },
  {
    title: 'Jollof Rice with Plantain',
    description: 'A flavorful West African one-pot dish made with rice, tomatoes, and spices, served with fried plantains.',
    cookingTime: 45,
    servings: 4,
    difficulty: 'MEDIUM',
    cuisineType: 'West African',
    regionOfOrigin: 'West Africa',
    imageUrl: '/images/recipes/vegan-jollof-rice.jpg',
    calories: 350,
    type: 'DINNER',
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    isDairyFree: true,
    isNutFree: true,
    ingredients: [
      { name: 'Long-grain rice', amount: 2, unit: 'cups', notes: 'washed and drained' },
      { name: 'Tomatoes', amount: 4, unit: 'large', notes: 'blended into a puree' },
      { name: 'Red bell pepper', amount: 1, unit: 'large', notes: 'blended into a puree' },
      { name: 'Onion', amount: 1, unit: 'medium', notes: 'chopped' },
      { name: 'Garlic', amount: 3, unit: 'cloves', notes: 'minced' },
      { name: 'Ginger', amount: 1, unit: 'tablespoon', notes: 'minced' },
      { name: 'Vegetable oil', amount: 3, unit: 'tablespoons' },
      { name: 'Tomato paste', amount: 2, unit: 'tablespoons' },
      { name: 'Vegetable stock', amount: 4, unit: 'cups' },
      { name: 'Thyme', amount: 1, unit: 'teaspoon' },
      { name: 'Curry powder', amount: 1, unit: 'teaspoon' },
      { name: 'Bay leaves', amount: 2, unit: 'leaves' },
      { name: 'Scotch bonnet pepper', amount: 1, unit: 'pepper', notes: 'optional, for heat' },
      { name: 'Salt', amount: 1, unit: 'teaspoon', notes: 'to taste' },
      { name: 'Black pepper', amount: 0.5, unit: 'teaspoon', notes: 'to taste' },
      { name: 'Ripe plantains', amount: 2, unit: 'large', notes: 'sliced and fried' }
    ],
    instructions: [
      { stepNumber: 1, description: 'Heat vegetable oil in a large pot over medium heat.' },
      { stepNumber: 2, description: 'Add chopped onions and sauté until translucent.' },
      { stepNumber: 3, description: 'Add minced garlic and ginger, and cook for 1-2 minutes until fragrant.' },
      { stepNumber: 4, description: 'Stir in tomato paste and cook for 2-3 minutes to deepen the flavor.' },
      { stepNumber: 5, description: 'Add blended tomatoes and red bell pepper, and cook for 10 minutes until the mixture thickens.' },
      { stepNumber: 6, description: 'Add thyme, curry powder, bay leaves, Scotch bonnet pepper (if using), salt, and black pepper. Stir well.' },
      { stepNumber: 7, description: 'Pour in the vegetable stock and bring to a boil.' },
      { stepNumber: 8, description: 'Add the washed rice, stir, and reduce the heat to low. Cover and simmer for 20-25 minutes until the rice is cooked and the liquid is absorbed.' },
      { stepNumber: 9, description: 'While the rice is cooking, fry the sliced plantains in oil until golden brown on both sides.' },
      { stepNumber: 10, description: 'Fluff the rice with a fork, remove the bay leaves, and serve hot with fried plantains on the side.' }
    ],
    nutritionFacts: {
      protein: 6,
      carbs: 70,
      fat: 8,
      fiber: 4,
      sugar: 10,
      sodium: 600
    }
  },
  {
    title: 'Hilsa Fish Curry (Ilish Bhapa)',
    description: 'A traditional Bengali dish made with Hilsa fish, steamed in a mustard and coconut paste. A staple during festivals and special occasions.',
    cookingTime: 30,
    servings: 4,
    difficulty: 'MEDIUM',
    cuisineType: 'South Asian',
    regionOfOrigin: 'Bangladesh',
    imageUrl: '/images/recipes/hilsa-fish-curry.jpg',
    calories: 300,
    type: 'MAIN',
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: true,
    isDairyFree: true,
    isNutFree: true,
    ingredients: [
      { name: 'Hilsa fish', amount: 4, unit: 'pieces' },
      { name: 'Mustard paste', amount: 3, unit: 'tablespoons' },
      { name: 'Coconut paste', amount: 2, unit: 'tablespoons' },
      { name: 'Green chilies', amount: 4, unit: 'pieces', notes: 'slit' },
      { name: 'Turmeric powder', amount: 1, unit: 'teaspoon' },
      { name: 'Mustard oil', amount: 3, unit: 'tablespoons' },
      { name: 'Salt', amount: 1, unit: 'teaspoon', notes: 'to taste' }
    ],
    instructions: [
      { stepNumber: 1, description: 'Marinate the Hilsa fish with turmeric and salt for 10 minutes.' },
      { stepNumber: 2, description: 'Mix mustard paste, coconut paste, and green chilies in a bowl.' },
      { stepNumber: 3, description: 'Coat the fish with the mustard-coconut mixture.' },
      { stepNumber: 4, description: 'Heat mustard oil in a pan and add the marinated fish.' },
      { stepNumber: 5, description: 'Cover and steam on low heat for 15-20 minutes until the fish is cooked.' },
      { stepNumber: 6, description: 'Serve hot with steamed rice.' }
    ],
    nutritionFacts: {
      protein: 25,
      carbs: 10,
      fat: 18,
      fiber: 2,
      sugar: 1,
      sodium: 500
    }
  },
  {
    title: 'Panta Bhat with Fried Hilsa (Panta Ilish)',
    description: 'A rustic dish of fermented rice soaked in water, paired with fried Hilsa fish. A traditional meal for Pohela Boishakh (Bengali New Year).',
    cookingTime: 20,
    servings: 4,
    difficulty: 'EASY',
    cuisineType: 'South Asian',
    regionOfOrigin: 'Bangladesh',
    imageUrl: '/images/recipes/panta-bhat.jpg',
    calories: 400,
    type: 'MAIN',
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: true,
    isDairyFree: true,
    isNutFree: true,
    ingredients: [
      { name: 'Leftover rice', amount: 4, unit: 'cups' },
      { name: 'Water', amount: 4, unit: 'cups' },
      { name: 'Hilsa fish', amount: 4, unit: 'pieces' },
      { name: 'Turmeric powder', amount: 1, unit: 'teaspoon' },
      { name: 'Salt', amount: 1, unit: 'teaspoon', notes: 'to taste' },
      { name: 'Mustard oil', amount: 3, unit: 'tablespoons' },
      { name: 'Green chilies', amount: 4, unit: 'pieces' },
      { name: 'Onions', amount: 1, unit: 'medium', notes: 'sliced' }
    ],
    instructions: [
      { stepNumber: 1, description: 'Soak the leftover rice in water overnight to ferment.' },
      { stepNumber: 2, description: 'Marinate the Hilsa fish with turmeric and salt.' },
      { stepNumber: 3, description: 'Heat mustard oil in a pan and fry the fish until golden brown.' },
      { stepNumber: 4, description: 'Serve the fermented rice (Panta Bhat) with fried Hilsa, green chilies, and sliced onions.' }
    ],
    nutritionFacts: {
      protein: 20,
      carbs: 60,
      fat: 12,
      fiber: 3,
      sugar: 2,
      sodium: 400
    }
  },
  {
    title: 'Beef Tehari',
    description: 'A flavorful rice dish made with beef, aromatic spices, and fragrant rice. A popular street food and comfort meal in Bangladesh.',
    cookingTime: 60,
    servings: 4,
    difficulty: 'MEDIUM',
    cuisineType: 'South Asian',
    regionOfOrigin: 'Bangladesh',
    imageUrl: '/images/recipes/beef-tehari.jpg',
    calories: 450,
    type: 'MAIN',
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: true,
    isDairyFree: true,
    isNutFree: true,
    ingredients: [
      { name: 'Beef', amount: 500, unit: 'grams', notes: 'cut into cubes' },
      { name: 'Basmati rice', amount: 2, unit: 'cups', notes: 'washed and drained' },
      { name: 'Onion', amount: 2, unit: 'medium', notes: 'sliced' },
      { name: 'Ginger-garlic paste', amount: 2, unit: 'tablespoons' },
      { name: 'Yogurt', amount: 1, unit: 'cup' },
      { name: 'Turmeric powder', amount: 1, unit: 'teaspoon' },
      { name: 'Cumin powder', amount: 1, unit: 'teaspoon' },
      { name: 'Cardamom pods', amount: 4, unit: 'pieces' },
      { name: 'Bay leaves', amount: 2, unit: 'leaves' },
      { name: 'Mustard oil', amount: 3, unit: 'tablespoons' },
      { name: 'Salt', amount: 1, unit: 'teaspoon', notes: 'to taste' }
    ],
    instructions: [
      { stepNumber: 1, description: 'Marinate the beef with yogurt, ginger-garlic paste, turmeric, and salt for 30 minutes.' },
      { stepNumber: 2, description: 'Heat mustard oil in a pot and sauté the onions until golden brown.' },
      { stepNumber: 3, description: 'Add the marinated beef and cook until browned.' },
      { stepNumber: 4, description: 'Add cumin powder, cardamom pods, and bay leaves. Stir well.' },
      { stepNumber: 5, description: 'Add the rice and enough water to cook. Cover and simmer for 20-25 minutes.' },
      { stepNumber: 6, description: 'Fluff the rice and serve hot, garnished with fried onions.' }
    ],
    nutritionFacts: {
      protein: 30,
      carbs: 50,
      fat: 15,
      fiber: 3,
      sugar: 2,
      sodium: 600
    }
  },
  {
    title: 'Chitol Macher Muitha (Fish Kofta Curry)',
    description: 'A delicacy made with minced Chitol fish, shaped into koftas (dumplings), and cooked in a rich, spicy gravy.',
    cookingTime: 50,
    servings: 4,
    difficulty: 'MEDIUM',
    cuisineType: 'South Asian',
    regionOfOrigin: 'Bangladesh',
    imageUrl: '/images/recipes/chitol-macher-muitha.jpg',
    calories: 350,
    type: 'MAIN',
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: true,
    isDairyFree: true,
    isNutFree: true,
    ingredients: [
      { name: 'Chitol fish', amount: 500, unit: 'grams', notes: 'minced' },
      { name: 'Onion', amount: 2, unit: 'medium', notes: 'finely chopped' },
      { name: 'Garlic paste', amount: 1, unit: 'tablespoon' },
      { name: 'Ginger paste', amount: 1, unit: 'tablespoon' },
      { name: 'Turmeric powder', amount: 1, unit: 'teaspoon' },
      { name: 'Chili powder', amount: 1, unit: 'teaspoon' },
      { name: 'Mustard oil', amount: 4, unit: 'tablespoons' },
      { name: 'Salt', amount: 1, unit: 'teaspoon', notes: 'to taste' },
      { name: 'Coriander leaves', amount: 1, unit: 'handful', notes: 'chopped' }
    ],
    instructions: [
      { stepNumber: 1, description: 'Mix minced fish, half of the chopped onions, garlic paste, ginger paste, turmeric, chili powder, and salt. Shape into koftas.' },
      { stepNumber: 2, description: 'Heat mustard oil in a pan and fry the koftas until golden. Set aside.' },
      { stepNumber: 3, description: 'In the same oil, sauté the remaining onions until golden.' },
      { stepNumber: 4, description: 'Add the fried koftas and cook in the gravy for 10-15 minutes.' },
      { stepNumber: 5, description: 'Garnish with coriander leaves and serve hot with rice.' }
    ],
    nutritionFacts: {
      protein: 28,
      carbs: 15,
      fat: 20,
      fiber: 2,
      sugar: 3,
      sodium: 500
    }
  },
  {
    title: 'Shorshe Bata Maach (Mustard Fish Curry)',
    description: 'A classic Bengali dish where fish is cooked in a pungent and flavorful mustard sauce. A signature dish of Bangladeshi cuisine.',
    cookingTime: 30,
    servings: 4,
    difficulty: 'MEDIUM',
    cuisineType: 'South Asian',
    regionOfOrigin: 'Bangladesh',
    imageUrl: '/images/recipes/shorshe-bata-maach.jpg',
    calories: 280,
    type: 'MAIN',
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: true,
    isDairyFree: true,
    isNutFree: true,
    ingredients: [
      { name: 'Rohu or Katla fish', amount: 4, unit: 'pieces' },
      { name: 'Mustard seeds', amount: 3, unit: 'tablespoons' },
      { name: 'Green chilies', amount: 4, unit: 'pieces' },
      { name: 'Turmeric powder', amount: 1, unit: 'teaspoon' },
      { name: 'Mustard oil', amount: 4, unit: 'tablespoons' },
      { name: 'Salt', amount: 1, unit: 'teaspoon', notes: 'to taste' }
    ],
    instructions: [
      { stepNumber: 1, description: 'Grind mustard seeds and green chilies into a smooth paste.' },
      { stepNumber: 2, description: 'Marinate the fish with turmeric and salt.' },
      { stepNumber: 3, description: 'Heat mustard oil in a pan and fry the fish lightly. Set aside.' },
      { stepNumber: 4, description: 'In the same oil, add the mustard paste and cook for 2-3 minutes.' },
      { stepNumber: 5, description: 'Add the fish and simmer for 10-15 minutes until cooked.' },
      { stepNumber: 6, description: 'Serve hot with steamed rice.' }
    ],
    nutritionFacts: {
      protein: 22,
      carbs: 8,
      fat: 18,
      fiber: 1,
      sugar: 1,
      sodium: 400
    }
  },
  {
    title: 'Amala with Ewedu, Gbegiri and Assorted Stew',
    description: 'A classic Nigerian dish featuring smooth, dark-brown yam flour dough (amala) served with viscous jute leaves soup (ewedu), creamy bean soup (gbegiri), and rich assorted meat stew. This traditional Yoruba combination is known for its rich flavors and cultural significance.',
    cookingTime: 60,
    servings: 4,
    difficulty: 'MEDIUM',
    cuisineType: 'West African',
    regionOfOrigin: 'Nigeria',
    imageUrl: '/images/recipes/amala-ewedu-gbegiri.jpg',
    calories: 550,
    type: 'MAIN',
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: true,
    isDairyFree: true,
    isNutFree: true,
    ingredients: [
      // Amala
      { name: 'Yam flour (elubo)', amount: 2, unit: 'cups' },
      { name: 'Hot water', amount: 4, unit: 'cups' },
      // Ewedu Soup
      { name: 'Fresh ewedu leaves', amount: 8, unit: 'ounces' },
      { name: 'Locust beans', amount: 2, unit: 'tablespoons' },
      { name: 'Ground crayfish', amount: 2, unit: 'tablespoons' },
      { name: 'Bouillon powder', amount: 1, unit: 'teaspoon' },
      // Gbegiri
      { name: 'Brown beans', amount: 2, unit: 'cups' },
      { name: 'Onions', amount: 1, unit: 'medium' },
      { name: 'Palm oil', amount: 3, unit: 'tablespoons' },
      { name: 'Scotch bonnet pepper', amount: 2, unit: 'pieces' },
      // Assorted Stew
      { name: 'Assorted meat', amount: 1, unit: 'kg', notes: 'beef, tripe, and cow skin (kpomo)' },
      { name: 'Red bell peppers', amount: 4, unit: 'large' },
      { name: 'Tomatoes', amount: 6, unit: 'medium' },
      { name: 'Onions', amount: 2, unit: 'large' },
      { name: 'Palm oil', amount: 1, unit: 'cup' },
      { name: 'Curry powder', amount: 1, unit: 'tablespoon' },
      { name: 'Thyme', amount: 1, unit: 'teaspoon' },
      { name: 'Bay leaves', amount: 2, unit: 'pieces' },
      { name: 'Salt', amount: 1, unit: 'teaspoon', notes: 'to taste' }
    ],
    instructions: [
      // Amala
      { stepNumber: 1, description: 'Boil water in a pot and remove from heat.' },
      { stepNumber: 2, description: 'Gradually add yam flour while stirring continuously to avoid lumps.' },
      { stepNumber: 3, description: 'Return to low heat and keep stirring until smooth and well-cooked, about 10 minutes.' },
      // Ewedu
      { stepNumber: 4, description: 'Clean and blend ewedu leaves with locust beans and crayfish until smooth.' },
      { stepNumber: 5, description: 'Cook the blended mixture for 5 minutes, adding bouillon and salt to taste.' },
      // Gbegiri
      { stepNumber: 6, description: 'Cook and peel brown beans, then blend until smooth.' },
      { stepNumber: 7, description: 'Sauté onions in palm oil, add blended beans, and simmer for 15 minutes.' },
      { stepNumber: 8, description: 'Season with pepper and salt to taste.' },
      // Assorted Stew
      { stepNumber: 9, description: 'Season and cook assorted meat until tender, reserving the stock.' },
      { stepNumber: 10, description: 'Blend peppers, tomatoes, and onions into a smooth paste.' },
      { stepNumber: 11, description: 'Heat palm oil in a large pot and fry the blended mixture until reduced and oil floats to top.' },
      { stepNumber: 12, description: 'Add cooked meat, stock, curry powder, thyme, and bay leaves.' },
      { stepNumber: 13, description: 'Simmer until stew thickens and oil rises to the surface.' },
      { stepNumber: 14, description: 'Serve amala hot with ewedu, gbegiri, and assorted stew arranged in separate bowls.' }
    ],
    nutritionFacts: {
      protein: 25,
      carbs: 65,
      fat: 20,
      fiber: 8,
      sugar: 3,
      sodium: 450
    }
  },
  {
    title: 'Iyan (Pounded Yam) with Egusi Soup',
    description: 'A hearty Nigerian dish featuring smooth, elastic pounded yam served with rich melon seed soup. This combination is a staple of Nigerian cuisine, particularly popular among the Yoruba people.',
    cookingTime: 60,
    servings: 4,
    difficulty: 'MEDIUM',
    cuisineType: 'West African',
    regionOfOrigin: 'Nigeria',
    imageUrl: '/images/recipes/iyan-egusi.jpg',
    calories: 550,
    type: 'MAIN',
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: true,
    isDairyFree: true,
    isNutFree: false,
    ingredients: [
      // Iyan
      { name: 'White yam', amount: 1, unit: 'kg', notes: 'peeled and cut into chunks' },
      { name: 'Water', amount: 4, unit: 'cups', notes: 'for boiling' },
      // Egusi Soup
      { name: 'Ground egusi (melon seeds)', amount: 2, unit: 'cups' },
      { name: 'Palm oil', amount: 1/2, unit: 'cup' },
      { name: 'Beef', amount: 500, unit: 'grams', notes: 'cut into chunks' },
      { name: 'Stockfish', amount: 100, unit: 'grams' },
      { name: 'Dried fish', amount: 100, unit: 'grams' },
      { name: 'Spinach or bitter leaf', amount: 2, unit: 'cups', notes: 'chopped' },
      { name: 'Onions', amount: 2, unit: 'medium' },
      { name: 'Ground crayfish', amount: 3, unit: 'tablespoons' },
      { name: 'Scotch bonnet pepper', amount: 2, unit: 'pieces' },
      { name: 'Bouillon cubes', amount: 2, unit: 'pieces' },
      { name: 'Salt', amount: 1, unit: 'teaspoon', notes: 'to taste' }
    ],
    instructions: [
      // Iyan
      { stepNumber: 1, description: 'Boil yam chunks until very soft and easily pierced with a fork.' },
      { stepNumber: 2, description: 'Pound the hot yam in a mortar with a pestle until smooth and elastic.' },
      { stepNumber: 3, description: 'Continue pounding until no lumps remain and the yam becomes stretchy.' },
      // Egusi Soup
      { stepNumber: 4, description: 'Season and cook meat and fish until tender, reserving the stock.' },
      { stepNumber: 5, description: 'Heat palm oil in a pot and sauté chopped onions.' },
      { stepNumber: 6, description: 'Add ground egusi and fry until fragrant, about 5 minutes.' },
      { stepNumber: 7, description: 'Add meat stock, cooked meat, fish, and crayfish.' },
      { stepNumber: 8, description: 'Simmer for 10 minutes, then add chopped vegetables.' },
      { stepNumber: 9, description: 'Cook for additional 5 minutes and adjust seasoning.' },
      { stepNumber: 10, description: 'Serve hot pounded yam with the egusi soup.' }
    ],
    nutritionFacts: {
      protein: 25,
      carbs: 70,
      fat: 28,
      fiber: 6,
      sugar: 2,
      sodium: 450
    }
  },
  {
    title: 'Eba and Ila (Okra) Soup',
    description: 'A traditional Nigerian meal featuring smooth cassava flour dough (eba) served with viscous okra soup. This combination is loved for its slippery texture and rich flavor profile.',
    cookingTime: 40,
    servings: 4,
    difficulty: 'EASY',
    cuisineType: 'West African',
    regionOfOrigin: 'Nigeria',
    imageUrl: '/images/recipes/eba-okra.jpg',
    calories: 400,
    type: 'MAIN',
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: true,
    isDairyFree: true,
    isNutFree: true,
    ingredients: [
      // Eba
      { name: 'Garri (cassava flour)', amount: 2, unit: 'cups' },
      { name: 'Hot water', amount: 3, unit: 'cups' },
      // Okra Soup
      { name: 'Fresh okra', amount: 15, unit: 'pieces', notes: 'finely chopped' },
      { name: 'Palm oil', amount: 1/4, unit: 'cup' },
      { name: 'Beef', amount: 300, unit: 'grams', notes: 'cut into chunks' },
      { name: 'Smoked fish', amount: 200, unit: 'grams' },
      { name: 'Ground crayfish', amount: 2, unit: 'tablespoons' },
      { name: 'Onions', amount: 1, unit: 'medium' },
      { name: 'Scotch bonnet pepper', amount: 1, unit: 'piece' },
      { name: 'Spinach', amount: 2, unit: 'cups', notes: 'chopped' },
      { name: 'Bouillon cubes', amount: 2, unit: 'pieces' },
      { name: 'Salt', amount: 1, unit: 'teaspoon', notes: 'to taste' }
    ],
    instructions: [
      // Eba
      { stepNumber: 1, description: 'Boil water in a kettle or pot.' },
      { stepNumber: 2, description: 'Pour hot water into a bowl and gradually add garri while stirring vigorously.' },
      { stepNumber: 3, description: 'Continue stirring until smooth and firm, with no lumps.' },
      // Okra Soup
      { stepNumber: 4, description: 'Cook meat with onions and seasonings until tender.' },
      { stepNumber: 5, description: 'Heat palm oil in a pot and sauté remaining onions.' },
      { stepNumber: 6, description: 'Add chopped okra and cook for 5 minutes, stirring occasionally.' },
      { stepNumber: 7, description: 'Add meat stock, cooked meat, and smoked fish.' },
      { stepNumber: 8, description: 'Add crayfish, pepper, and seasonings.' },
      { stepNumber: 9, description: 'Simmer for 5 minutes, then add chopped spinach.' },
      { stepNumber: 10, description: 'Cook for 2 more minutes and serve hot with eba.' }
    ],
    nutritionFacts: {
      protein: 18,
      carbs: 60,
      fat: 15,
      fiber: 7,
      sugar: 2,
      sodium: 380
    }
  },
  {
    title: 'Ofada Rice and Ayamase (Green Pepper Stew)',
    description: 'A premium Nigerian dish featuring locally grown brown rice served with a rich, spicy green pepper stew. This dish is a favorite in Yoruba cuisine, particularly popular in Lagos and Ogun states.',
    cookingTime: 75,
    servings: 6,
    difficulty: 'MEDIUM',
    cuisineType: 'West African',
    regionOfOrigin: 'Nigeria',
    imageUrl: '/images/recipes/ofada-ayamase.jpg',
    calories: 520,
    type: 'MAIN',
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: true,
    isDairyFree: true,
    isNutFree: true,
    ingredients: [
      // Ofada Rice
      { name: 'Ofada rice', amount: 3, unit: 'cups' },
      { name: 'Onion', amount: 1, unit: 'small', notes: 'chopped' },
      { name: 'Salt', amount: 1, unit: 'teaspoon' },
      // Ayamase
      { name: 'Green bell peppers', amount: 6, unit: 'large' },
      { name: 'Green scotch bonnet peppers', amount: 4, unit: 'pieces' },
      { name: 'Palm oil', amount: 1, unit: 'cup' },
      { name: 'Assorted meat', amount: 1, unit: 'kg', notes: 'beef, tripe, and cow skin' },
      { name: 'Locust beans', amount: 3, unit: 'tablespoons' },
      { name: 'Onions', amount: 3, unit: 'medium' },
      { name: 'Ground crayfish', amount: 2, unit: 'tablespoons' },
      { name: 'Bouillon cubes', amount: 3, unit: 'pieces' },
      { name: 'Salt', amount: 1, unit: 'teaspoon', notes: 'to taste' }
    ],
    instructions: [
      // Ofada Rice
      { stepNumber: 1, description: 'Carefully pick stones from ofada rice and wash thoroughly until water runs clear.' },
      { stepNumber: 2, description: 'Cook rice with plenty of water, chopped onions, and salt until tender but not mushy.' },
      // Ayamase
      { stepNumber: 3, description: 'Blend green peppers and scotch bonnets into a coarse paste.' },
      { stepNumber: 4, description: 'Season and cook assorted meat until tender, reserving the stock.' },
      { stepNumber: 5, description: 'Carefully bleach palm oil on low heat until transparent (about 30 minutes).' },
      { stepNumber: 6, description: 'Sauté onions and locust beans in bleached oil.' },
      { stepNumber: 7, description: 'Add cooked meat and fry for 5 minutes.' },
      { stepNumber: 8, description: 'Add blended peppers and cook until oil floats to top.' },
      { stepNumber: 9, description: 'Season with crayfish, bouillon, and salt.' },
      { stepNumber: 10, description: 'Simmer until stew is well reduced and oil is visible on top.' }
    ],
    nutritionFacts: {
      protein: 28,
      carbs: 65,
      fat: 25,
      fiber: 4,
      sugar: 3,
      sodium: 420
    }
  },
  {
    title: 'Moin Moin (Steamed Bean Pudding) with Pap',
    description: 'A nutritious Nigerian breakfast combination featuring steamed bean pudding made from peeled black-eyed peas, served with smooth, fermented corn porridge (pap/ogi). This protein-rich meal is a beloved Nigerian breakfast.',
    cookingTime: 90,
    servings: 6,
    difficulty: 'MEDIUM',
    cuisineType: 'West African',
    regionOfOrigin: 'Nigeria',
    imageUrl: '/images/recipes/moinmoin-pap.jpg',
    calories: 380,
    type: 'BREAKFAST',
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    isDairyFree: true,
    isNutFree: true,
    ingredients: [
      // Moin Moin
      { name: 'Black-eyed peas', amount: 2, unit: 'cups', notes: 'peeled' },
      { name: 'Red bell peppers', amount: 2, unit: 'medium' },
      { name: 'Onions', amount: 2, unit: 'medium' },
      { name: 'Scotch bonnet pepper', amount: 1, unit: 'piece' },
      { name: 'Vegetable oil', amount: 1/2, unit: 'cup' },
      { name: 'Bouillon cubes', amount: 2, unit: 'pieces' },
      { name: 'Salt', amount: 1, unit: 'teaspoon', notes: 'to taste' },
      // Pap
      { name: 'White corn pap', amount: 2, unit: 'cups' },
      { name: 'Water', amount: 4, unit: 'cups' },
      { name: 'Sugar', amount: 2, unit: 'tablespoons', notes: 'optional' }
    ],
    instructions: [
      // Moin Moin
      { stepNumber: 1, description: 'Soak and peel beans, then blend with peppers and onions until smooth.' },
      { stepNumber: 2, description: 'Add oil, seasonings, and salt to the mixture and blend again.' },
      { stepNumber: 3, description: 'Pour into greased molds or leaves.' },
      { stepNumber: 4, description: 'Steam for 45-60 minutes until firm.' },
      // Pap
      { stepNumber: 5, description: 'Mix pap powder with cold water to form a smooth paste.' },
      { stepNumber: 6, description: 'Boil remaining water and gradually add to pap mixture, stirring constantly.' },
      { stepNumber: 7, description: 'Cook while stirring until thickened to desired consistency.' },
      { stepNumber: 8, description: 'Add sugar if desired.' },
      { stepNumber: 9, description: 'Serve hot moin moin with warm pap.' }
    ],
    nutritionFacts: {
      protein: 15,
      carbs: 55,
      fat: 12,
      fiber: 8,
      sugar: 5,
      sodium: 300
    }
  },
  {
    title: 'Couscous with Vegetables and Meat',
    description: 'A traditional North African dish featuring fluffy couscous topped with tender vegetables, aromatic spices, and succulent meat in a flavorful broth.',
    cookingTime: 90,
    servings: 6,
    difficulty: 'MEDIUM',
    cuisineType: 'North African',
    regionOfOrigin: 'North Africa',
    imageUrl: 'https://www.thespruceeats.com/thmb/A7dwS7Y3yh3IeQ1NZEWZ45KGH4c=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/couscous-getty-3890-x-2562-56a645de5f9b58b7d0e0c3b1-af93f1c24efb43b9a3c143eba611aabd.jpg',
    calories: 450,
    type: 'DINNER',
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: false,
    isDairyFree: true,
    isNutFree: true,
    ingredients: [
      { name: 'Couscous', amount: 2, unit: 'cups' },
      { name: 'Lamb or beef', amount: 1.5, unit: 'pounds', notes: 'cut into chunks' },
      { name: 'Carrots', amount: 4, unit: 'medium', notes: 'cut into large pieces' },
      { name: 'Zucchini', amount: 2, unit: 'medium', notes: 'cut into large pieces' },
      { name: 'Chickpeas', amount: 1, unit: 'can', notes: 'drained and rinsed' },
      { name: 'Onions', amount: 2, unit: 'large', notes: 'chopped' },
      { name: 'Tomatoes', amount: 2, unit: 'large', notes: 'chopped' },
      { name: 'Ras el hanout', amount: 2, unit: 'tablespoons' },
      { name: 'Turmeric', amount: 1, unit: 'teaspoon' },
      { name: 'Olive oil', amount: 3, unit: 'tablespoons' }
    ],
    instructions: [
      { stepNumber: 1, description: 'Season meat with ras el hanout, salt, and pepper. Brown in olive oil in a large pot.' },
      { stepNumber: 2, description: 'Add chopped onions and cook until softened.' },
      { stepNumber: 3, description: 'Add tomatoes, turmeric, and enough water to cover. Simmer for 45 minutes.' },
      { stepNumber: 4, description: 'Add carrots and chickpeas, cook for 15 minutes.' },
      { stepNumber: 5, description: 'Add zucchini and cook for another 10 minutes until vegetables are tender.' },
      { stepNumber: 6, description: 'Meanwhile, prepare couscous according to package instructions.' },
      { stepNumber: 7, description: 'Fluff couscous with a fork and arrange on a serving platter.' },
      { stepNumber: 8, description: 'Top with meat and vegetables, then ladle broth over the dish.' }
    ],
    nutritionFacts: {
      protein: 28,
      carbs: 52,
      fat: 16,
      fiber: 8,
      sugar: 6,
      sodium: 480
    }
  },
  {
    title: 'Chakhchoukha',
    description: 'A hearty Algerian dish made with torn pieces of flatbread soaked in a spicy tomato-based sauce, often served with meat and vegetables.',
    cookingTime: 60,
    servings: 4,
    difficulty: 'MEDIUM',
    cuisineType: 'algerian',
    regionOfOrigin: 'Algeria',
    imageUrl: 'https://theodehlicious.com/wp-content/uploads/2023/11/Algerian-Chakhchoukha-II.jpg',
    calories: 400,
    type: 'MAIN',
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: false,
    isDairyFree: true,
    isNutFree: true,
    ingredients: [
      { name: 'Flatbread (rougag or markouk)', amount: 4, unit: 'pieces' },
      { name: 'Lamb or chicken', amount: 500, unit: 'grams' },
      { name: 'Tomatoes', amount: 4, unit: 'large' },
      { name: 'Onion', amount: 1, unit: 'medium' },
      { name: 'Garlic', amount: 3, unit: 'cloves' },
      { name: 'Chili pepper', amount: 1, unit: 'piece' },
      { name: 'Olive oil', amount: 3, unit: 'tablespoons' },
      { name: 'Spices (cumin, paprika)', amount: 1, unit: 'teaspoon each' },
      { name: 'Salt', amount: 1, unit: 'teaspoon', notes: 'to taste' }
    ],
    instructions: [
      { stepNumber: 1, description: 'Tear the flatbread into small pieces and set aside.' },
      { stepNumber: 2, description: 'In a pot, heat olive oil and sauté onions, garlic, and chili pepper.' },
      { stepNumber: 3, description: 'Add the meat and brown on all sides.' },
      { stepNumber: 4, description: 'Add chopped tomatoes, spices, and salt. Simmer for 30 minutes.' },
      { stepNumber: 5, description: 'Add the torn flatbread to the sauce and mix well.' },
      { stepNumber: 6, description: 'Serve hot as a main dish.' }
    ],
    nutritionFacts: {
      protein: 20,
      carbs: 50,
      fat: 15,
      fiber: 6,
      sugar: 5,
      sodium: 500
    }
  },
  {
    title: 'Rechta',
    description: 'A traditional Algerian pasta dish made with thin handmade noodles, served with a white sauce made from chicken or meat and vegetables.',
    cookingTime: 90,
    servings: 4,
    difficulty: 'MEDIUM',
    cuisineType: 'algerian',
    regionOfOrigin: 'Algeria',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/7/76/Rechta_tunisienne.jpg?20230519044949',
    calories: 500,
    type: 'MAIN',
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: false,
    isDairyFree: true,
    isNutFree: true,
    ingredients: [
      { name: 'Rechta noodles', amount: 2, unit: 'cups' },
      { name: 'Chicken or lamb', amount: 500, unit: 'grams' },
      { name: 'Onion', amount: 1, unit: 'medium' },
      { name: 'Garlic', amount: 3, unit: 'cloves' },
      { name: 'Chickpeas', amount: 1, unit: 'cup', notes: 'cooked' },
      { name: 'Turnip', amount: 1, unit: 'medium' },
      { name: 'Potatoes', amount: 2, unit: 'medium' },
      { name: 'Olive oil', amount: 3, unit: 'tablespoons' },
      { name: 'Spices (cinnamon, turmeric, bay leaves)', amount: 1, unit: 'teaspoon each' },
      { name: 'Salt', amount: 1, unit: 'teaspoon', notes: 'to taste' }
    ],
    instructions: [
      { stepNumber: 1, description: 'Cook the rechta noodles according to package instructions. Set aside.' },
      { stepNumber: 2, description: 'In a pot, heat olive oil and sauté onions and garlic.' },
      { stepNumber: 3, description: 'Add the meat and brown on all sides.' },
      { stepNumber: 4, description: 'Add chopped vegetables, chickpeas, spices, and enough water to cover. Simmer for 45 minutes.' },
      { stepNumber: 5, description: 'Serve the noodles topped with the meat and vegetable stew.' }
    ],
    nutritionFacts: {
      protein: 30,
      carbs: 70,
      fat: 15,
      fiber: 8,
      sugar: 5,
      sodium: 600
    }
  },
  {
    title: "Mhadjeb (Algerian Stuffed Pancakes)",
    description: 'A popular Algerian street food made with thin semolina pancakes stuffed with a flavorful mixture of onions, tomatoes, and spices.',
    cookingTime: 60,
    servings: 4,
    difficulty: 'MEDIUM',
    cuisineType: 'algerian',
    regionOfOrigin: 'Algeria',
    imageUrl: 'https://theafrikanstore.com/cdn/shop/articles/M_hadjeb-djoudjousemetauxfourneaux_720x@2x.webp?v=1693943087',
    calories: 300,
    type: 'SNACK',
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: false,
    isDairyFree: true,
    isNutFree: true,
    ingredients: [
      { name: 'Semolina', amount: 2, unit: 'cups' },
      { name: 'Water', amount: 1, unit: 'cup' },
      { name: 'Onions', amount: 2, unit: 'medium' },
      { name: 'Tomatoes', amount: 4, unit: 'large' },
      { name: 'Tomato paste', amount: 1, unit: 'tablespoon' },
      { name: 'Olive oil', amount: 3, unit: 'tablespoons' },
      { name: 'Spices (paprika, cumin)', amount: 1, unit: 'teaspoon each' },
      { name: 'Salt', amount: 1, unit: 'teaspoon', notes: 'to taste' }
    ],
    instructions: [
      { stepNumber: 1, description: 'Mix semolina and water to form a dough. Let it rest for 30 minutes.' },
      { stepNumber: 2, description: 'Sauté onions in olive oil until soft. Add tomatoes, tomato paste, and spices. Cook until thickened.' },
      { stepNumber: 3, description: 'Divide the dough into balls and roll out into thin circles.' },
      { stepNumber: 4, description: 'Place the filling on one half of the circle and fold over to seal.' },
      { stepNumber: 5, description: 'Cook on a hot griddle until golden brown on both sides.' },
      { stepNumber: 6, description: 'Serve warm as a snack or light meal.' }
    ],
    nutritionFacts: {
      protein: 8,
      carbs: 50,
      fat: 10,
      fiber: 4,
      sugar: 5,
      sodium: 400
    }
  },
  {
    title: 'Muamba de Galinha (Chicken Muamba)',
    description: 'A flavorful Angolan stew made with chicken, palm oil, okra, and garlic, often served with funge or rice.',
    cookingTime: 90,
    servings: 4,
    difficulty: 'MEDIUM',
    cuisineType: 'west-african',
    regionOfOrigin: 'Angola',
    imageUrl: 'https://jesseatsandtravels.com/wp-content/uploads/2018/03/africanpeanutstew.jpg',
    calories: 400,
    type: 'MAIN',
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: true,
    isDairyFree: true,
    isNutFree: true,
    ingredients: [
      { name: 'Chicken', amount: 1, unit: 'whole', notes: 'cut into pieces' },
      { name: 'Palm oil', amount: 4, unit: 'tablespoons' },
      { name: 'Okra', amount: 200, unit: 'grams' },
      { name: 'Garlic', amount: 4, unit: 'cloves' },
      { name: 'Onion', amount: 1, unit: 'large' },
      { name: 'Tomatoes', amount: 2, unit: 'large' },
      { name: 'Chili pepper', amount: 1, unit: 'piece' },
      { name: 'Water', amount: 2, unit: 'cups' },
      { name: 'Salt', amount: 1, unit: 'teaspoon', notes: 'to taste' }
    ],
    instructions: [
      { stepNumber: 1, description: 'Heat palm oil in a large pot. Add chopped onions and garlic, and sauté until fragrant.' },
      { stepNumber: 2, description: 'Add chicken pieces and brown on all sides.' },
      { stepNumber: 3, description: 'Add chopped tomatoes, chili pepper, and salt. Stir well.' },
      { stepNumber: 4, description: 'Add water and bring to a boil. Reduce heat and simmer for 30 minutes.' },
      { stepNumber: 5, description: 'Add okra and cook for another 20-30 minutes until the chicken is tender and the sauce thickens.' },
      { stepNumber: 6, description: 'Serve hot with funge or rice.' }
    ],
    nutritionFacts: {
      protein: 30,
      carbs: 15,
      fat: 25,
      fiber: 5,
      sugar: 4,
      sodium: 600
    }
  },
  {
    title: 'Calulu',
    description: 'A traditional Angolan dish made with dried fish or meat, tomatoes, okra, and eggplant, slow-cooked to perfection and served with funge or rice.',
    cookingTime: 120,
    servings: 4,
    difficulty: 'MEDIUM',
    cuisineType: 'west-african',
    regionOfOrigin: 'Angola',
    imageUrl: 'https://assets.tmecosys.com/image/upload/t_web767x639/img/recipe/ras/Assets/BB9056E2-2AAB-4748-936A-45B6E40075EC/Derivates/5eec90ab-dc43-4d91-8631-647514b9fd92.jpg',
    calories: 350,
    type: 'MAIN',
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: true,
    isDairyFree: true,
    isNutFree: true,
    ingredients: [
      { name: 'Dried fish or meat', amount: 500, unit: 'grams' },
      { name: 'Tomatoes', amount: 4, unit: 'large' },
      { name: 'Okra', amount: 200, unit: 'grams' },
      { name: 'Eggplant', amount: 1, unit: 'large' },
      { name: 'Palm oil', amount: 3, unit: 'tablespoons' },
      { name: 'Onion', amount: 1, unit: 'large' },
      { name: 'Garlic', amount: 4, unit: 'cloves' },
      { name: 'Chili pepper', amount: 1, unit: 'piece' },
      { name: 'Water', amount: 3, unit: 'cups' },
      { name: 'Salt', amount: 1, unit: 'teaspoon', notes: 'to taste' }
    ],
    instructions: [
      { stepNumber: 1, description: 'Soak the dried fish or meat in water for 30 minutes to rehydrate. Drain and set aside.' },
      { stepNumber: 2, description: 'Heat palm oil in a large pot. Sauté chopped onions and garlic until fragrant.' },
      { stepNumber: 3, description: 'Add the rehydrated fish or meat and brown lightly.' },
      { stepNumber: 4, description: 'Add chopped tomatoes, chili pepper, and salt. Stir well.' },
      { stepNumber: 5, description: 'Add water and bring to a boil. Reduce heat and simmer for 45 minutes.' },
      { stepNumber: 6, description: 'Add okra and eggplant. Cook for another 30 minutes until tender.' },
      { stepNumber: 7, description: 'Serve hot with funge or rice.' }
    ],
    nutritionFacts: {
      protein: 25,
      carbs: 20,
      fat: 18,
      fiber: 6,
      sugar: 5,
      sodium: 700
    }
  },
  {
    title: 'Mufete',
    description: 'A festive Angolan dish featuring grilled fish, beans, boiled plantains, and a spicy tomato sauce.',
    cookingTime: 60,
    servings: 4,
    difficulty: 'MEDIUM',
    cuisineType: 'west-african',
    regionOfOrigin: 'Angola',
    imageUrl: 'https://theafrikanstore.com/cdn/shop/articles/mufete-www.maxi.co.ao_1512x@2x.jpg?v=1696883963',
    calories: 450,
    type: 'MAIN',
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: true,
    isDairyFree: true,
    isNutFree: true,
    ingredients: [
      { name: 'Fresh fish (tilapia or mackerel)', amount: 4, unit: 'pieces' },
      { name: 'Beans', amount: 2, unit: 'cups', notes: 'cooked' },
      { name: 'Plantains', amount: 4, unit: 'pieces' },
      { name: 'Tomatoes', amount: 3, unit: 'large' },
      { name: 'Onion', amount: 1, unit: 'large' },
      { name: 'Chili pepper', amount: 1, unit: 'piece' },
      { name: 'Palm oil', amount: 3, unit: 'tablespoons' },
      { name: 'Salt', amount: 1, unit: 'teaspoon', notes: 'to taste' }
    ],
    instructions: [
      { stepNumber: 1, description: 'Grill the fish until cooked through. Set aside.' },
      { stepNumber: 2, description: 'Boil the plantains until tender. Set aside.' },
      { stepNumber: 3, description: 'In a pan, heat palm oil and sauté chopped onions and garlic.' },
      { stepNumber: 4, description: 'Add chopped tomatoes and chili pepper. Cook until the sauce thickens.' },
      { stepNumber: 5, description: 'Serve the grilled fish with boiled plantains, beans, and the spicy tomato sauce.' }
    ],
    nutritionFacts: {
      protein: 35,
      carbs: 50,
      fat: 15,
      fiber: 8,
      sugar: 10,
      sodium: 500
    }
  },
  {
    title: 'Kizaka (Cassava Leaves Stew)',
    description: 'A hearty Angolan stew made with pounded cassava leaves, palm oil, and often fish or meat, served with funge or rice.',
    cookingTime: 90,
    servings: 4,
    difficulty: 'MEDIUM',
    cuisineType: 'west-african',
    regionOfOrigin: 'Angola',
    imageUrl: 'https://cookingwithclaudy.com/wp-content/uploads/2023/11/20231103113714_IMG_6436.jpg',
    calories: 400,
    type: 'MAIN',
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: true,
    isDairyFree: true,
    isNutFree: true,
    ingredients: [
      { name: 'Cassava leaves', amount: 500, unit: 'grams' },
      { name: 'Palm oil', amount: 4, unit: 'tablespoons' },
      { name: 'Fish or meat', amount: 500, unit: 'grams' },
      { name: 'Garlic', amount: 4, unit: 'cloves' },
      { name: 'Onion', amount: 1, unit: 'large' },
      { name: 'Tomatoes', amount: 2, unit: 'large' },
      { name: 'Chili pepper', amount: 1, unit: 'piece' },
      { name: 'Water', amount: 3, unit: 'cups' },
      { name: 'Salt', amount: 1, unit: 'teaspoon', notes: 'to taste' }
    ],
    instructions: [
      { stepNumber: 1, description: 'Pound the cassava leaves until finely shredded. Set aside.' },
      { stepNumber: 2, description: 'Heat palm oil in a large pot. Sauté chopped onions and garlic until fragrant.' },
      { stepNumber: 3, description: 'Add the fish or meat and brown lightly.' },
      { stepNumber: 4, description: 'Add chopped tomatoes, chili pepper, and salt. Stir well.' },
      { stepNumber: 5, description: 'Add water and bring to a boil. Reduce heat and simmer for 30 minutes.' },
      { stepNumber: 6, description: 'Add the pounded cassava leaves and cook for another 30 minutes until tender.' },
      { stepNumber: 7, description: 'Serve hot with funge or rice.' }
    ],
    nutritionFacts: {
      protein: 20,
      carbs: 30,
      fat: 20,
      fiber: 8,
      sugar: 5,
      sodium: 600
    }
  },
  {
    title: "Suya (Spicy Grilled Meat Skewers)",
    description: "A popular Nigerian street food consisting of spiced, skewered beef grilled to perfection and served with a unique blend of ground peanuts and spices.",
    cookingTime: 45,
    servings: 4,
    difficulty: "MEDIUM",
    cuisineType: "west-african",
    regionOfOrigin: "Nigeria",
    imageUrl: "https://images.food52.com/kS86TDdWevsjAhRBpwotP75V43k=/2016x1344/filters:format(webp)/cc4dec59-c417-4bb8-aa37-74a0080c2a62--4796689247_8da1af91d1.jpg",
    calories: 350,
    type: "MAIN",
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: true,
    isDairyFree: true,
    isNutFree: false,
    ingredients: [
      { name: "Beef sirloin", amount: 1, unit: "pound" },
      { name: "Ground peanuts", amount: 1, unit: "cup" },
      { name: "Cayenne pepper", amount: 2, unit: "tablespoons" },
      { name: "Paprika", amount: 1, unit: "tablespoon" },
      { name: "Ginger powder", amount: 1, unit: "teaspoon" },
      { name: "Garlic powder", amount: 1, unit: "teaspoon" },
      { name: "Onion powder", amount: 1, unit: "teaspoon" },
      { name: "Bouillon cube", amount: 1, unit: "piece" },
      { name: "Salt", amount: 1, unit: "teaspoon" }
    ],
    instructions: [
      { stepNumber: 1, description: "Mix all the dry spices with ground peanuts to create the suya spice mix." },
      { stepNumber: 2, description: "Thread the beef strips onto skewers and coat generously with the spice mix." },
      { stepNumber: 3, description: "Let marinate for at least 30 minutes." },
      { stepNumber: 4, description: "Grill the skewers for 10-15 minutes, turning occasionally, until cooked through." },
      { stepNumber: 5, description: "Serve hot with extra suya spice mix, sliced onions, and tomatoes." }
    ],
    nutritionFacts: {
      protein: 28,
      carbs: 12,
      fat: 22,
      fiber: 3,
      sugar: 2,
      sodium: 450
    }
  },
  {
    title: "Waakye (Rice and Beans)",
    description: 'A beloved Ghanaian dish of rice and beans cooked with waakye leaves, served with various accompaniments.',
    cookingTime: 90,
    servings: 6,
    difficulty: 'MEDIUM',
    cuisineType: 'ghanaian',
    regionOfOrigin: 'Ghana',
    imageUrl: 'https://eatwellabi.com/wp-content/uploads/2021/09/Waakye-13.jpg',
    calories: 400,
    type: 'MAIN',
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    isDairyFree: true,
    isNutFree: true,
    ingredients: [
      { name: "Long grain rice", amount: 2, unit: "cups" },
      { name: "Black-eyed peas", amount: 1, unit: "cup" },
      { name: "Waakye leaves", amount: 4, unit: "pieces" },
      { name: "Baking soda", amount: 0.5, unit: "teaspoon" },
      { name: "Onion", amount: 1, unit: "medium" },
      { name: "Garlic", amount: 3, unit: "cloves" },
      { name: "Salt", amount: 1, unit: "teaspoon" }
    ],
    instructions: [
      { stepNumber: 1, description: "Boil the pre-soaked beans with waakye leaves until almost tender." },
      { stepNumber: 2, description: "Add rice, onions, garlic, and baking soda to the pot." },
      { stepNumber: 3, description: "Cook until rice is tender and has taken on a characteristic reddish-brown color." },
      { stepNumber: 4, description: "Season with salt to taste." },
      { stepNumber: 5, description: "Serve hot with shito (black pepper sauce), gari, and fried plantains." }
    ],
    nutritionFacts: {
      protein: 15,
      carbs: 72,
      fat: 2,
      fiber: 8,
      sugar: 3,
      sodium: 380
    }
  },
  {
    title: "Peri Peri Chicken",
    description: "A fiery and flavorful Mozambican dish featuring spatchcocked chicken marinated in a spicy peri peri sauce, grilled to crispy perfection.",
    cookingTime: 40,
    servings: 3,
    difficulty: "MEDIUM",
    cuisineType: "mozambican",
    regionOfOrigin: "Mozambique",
    imageUrl: "https://whatsinthepan.com/wp-content/uploads/2018/05/Peri-Peri-Chicken-2.jpg",
    calories: 400,
    type: "MAIN",
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: true,
    isDairyFree: true,
    isNutFree: true,
    ingredients: [
      { name: "Free-range chicken", amount: 1, unit: "whole" },
      { name: "Peri-Peri oil", amount: 4, unit: "tablespoons" },
      { name: "Peri-Peri spice", amount: 0.5, unit: "teaspoon" },
      { name: "Bird's-eye chili (Peri-Peri)", amount: 2, unit: "pieces" },
      { name: "Garlic", amount: 3, unit: "cloves" },
      { name: "Fresh ginger", amount: 0.5, unit: "teaspoon" },
      { name: "Lime or lemon juice", amount: 1, unit: "piece" },
      { name: "Salt", amount: 0.25, unit: "teaspoon" },
      { name: "Black pepper", amount: 0.25, unit: "teaspoon" },
      { name: "Olive oil", amount: 2, unit: "tablespoons" },
      { name: "Sweet smoked paprika", amount: 1, unit: "tablespoon" },
      { name: "White wine vinegar", amount: 2, unit: "tablespoons" },
      { name: "Worcestershire sauce", amount: 1, unit: "tablespoon" }
    ],
    instructions: [
      { stepNumber: 1, description: "Spatchcock the chicken by removing the backbone and flattening it. Ask your butcher to do this if needed." },
      { stepNumber: 2, description: "Score the chicken deeply to allow the marinade to penetrate." },
      { stepNumber: 3, description: "Pour peri peri oil over the chicken, rubbing it into all the cuts and on both sides. This helps with marination and prevents sticking." },
      { stepNumber: 4, description: "Sprinkle peri peri spice evenly over the chicken, ensuring it covers all cuts and both sides." },
      { stepNumber: 5, description: "In a bowl, mix bird's-eye chili, garlic, ginger, salt, pepper, and lime/lemon juice. Crush or grind into a paste and spread over the chicken." },
      { stepNumber: 6, description: "Marinate the chicken for at least 1 hour, or ideally overnight, for maximum flavor." },
      { stepNumber: 7, description: "Preheat the grill (braai) to 180°C (360°F)." },
      { stepNumber: 8, description: "Place the chicken on the grill, open-side up, and cook for 15 minutes. Flip and cook for another 15 minutes." },
      { stepNumber: 9, description: "Increase the heat to brown and crisp the skin for 5-10 minutes, ensuring it doesn't burn." },
      { stepNumber: 10, description: "Check for doneness by poking a knife into the leg or thigh. If the juices run clear, the chicken is cooked. If not, grill for an additional 5-10 minutes." },
      { stepNumber: 11, description: "Serve hot with your choice of sides, such as grilled vegetables or rice." }
    ],
    nutritionFacts: {
      protein: 35,
      carbs: 5,
      fat: 25,
      fiber: 1,
      sugar: 2,
      sodium: 500
    }
  },
  {
    title: "West African Peanut Soup (Groundnut Soup)",
    description: "A rich and spicy West African peanut stew made with braised meat, ground peanuts, and spinach, often served with rice or starchy sides like eba or pounded yam.",
    cookingTime: 120,
    servings: 8,
    difficulty: 'MEDIUM',
    cuisineType: 'west-african',
    regionOfOrigin: 'West Africa',
    imageUrl: 'https://i0.wp.com/www.yummymedley.com/wp-content/uploads/2017/07/Groundnut-soup.jpg?w=750&ssl=1',
    calories: 425,
    type: 'MAIN',
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: true,
    isDairyFree: true,
    isNutFree: false,
    ingredients: [
      { name: 'Stewing goat meat', amount: 2.5, unit: 'lbs' },
      { name: 'Red onion', amount: 1, unit: 'large' },
      { name: 'Bouillon', amount: 2, unit: 'teaspoons' },
      { name: 'Salt', amount: 1, unit: 'teaspoon' },
      { name: 'Raw skinned peanuts', amount: 2, unit: 'cups' },
      { name: 'Scotch bonnet or habanero peppers', amount: 3, unit: 'pieces' },
      { name: 'Chopped spinach', amount: 0.5, unit: 'lbs' },
      { name: 'Dried shrimp powder (crayfish)', amount: 2, unit: 'tablespoons' },
      { name: 'Palm oil', amount: 3, unit: 'tablespoons' },
      { name: 'Water', amount: 3, unit: 'cups' }
    ],
    instructions: [
      { stepNumber: 1, description: 'In a stew pot, braise the goat meat with sliced onions, bouillon, and salt over low-medium heat for 30-35 minutes, or until tender. For older or tougher meat, cook longer.' },
      { stepNumber: 2, description: 'Toast the raw peanuts in a pan over low heat, stirring continuously, until they turn toasty in color (15-25 minutes). Let cool completely.' },
      { stepNumber: 3, description: 'Grind the cooled peanuts into a rough powder using a blender, food processor, or mortar and pestle. Avoid blending into a butter.' },
      { stepNumber: 4, description: 'In a pot, mix the ground peanuts, braising liquid from the meat, and water (about 3 cups total). Add the chopped Scotch bonnet peppers. Bring to a gentle boil over low-medium heat, stirring continuously for 10 minutes to prevent burning.' },
      { stepNumber: 5, description: 'Adjust the consistency by adding more water for a lighter soup or less for a thicker stew. Note that the soup thickens as it cooks and cools.' },
      { stepNumber: 6, description: 'Add palm oil, braised meat, and dried shrimp powder (crayfish). Cook for another 5 minutes.' },
      { stepNumber: 7, description: 'Stir in the chopped spinach and simmer for 5 minutes on low heat, stirring occasionally to prevent burning.' },
      { stepNumber: 8, description: 'Remove from heat and serve hot with rice, eba, or pounded yam.' }
    ],
    nutritionFacts: {
      protein: 25,
      carbs: 15,
      fat: 30,
      fiber: 5,
      sugar: 3,
      sodium: 600
    }
  },
  {
    title: "Banku and Tilapia",
    description: "A classic Ghanaian dish featuring fermented corn and cassava dough (Banku), grilled tilapia, and a spicy hot sauce. A flavorful and hearty meal.",
    cookingTime: 120,
    servings: 4,
    difficulty: 'MEDIUM',
    cuisineType: 'ghanaian',
    regionOfOrigin: 'Ghana',
    imageUrl: 'https://arkcleorich.com/wp-content/uploads/2022/10/img_6389-scaled.jpeg',
    calories: 600,
    type: 'MAIN',
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: true,
    isDairyFree: true,
    isNutFree: true,
    ingredients: [
      { name: 'Corn dough', amount: 2, unit: 'cups' },
      { name: 'Cassava dough', amount: 1, unit: 'cup' },
      { name: 'Water', amount: 4, unit: 'cups' },
      { name: 'Salt', amount: 1, unit: 'teaspoon' },
      { name: 'Tilapia', amount: 4, unit: 'pieces' },
      { name: 'Garlic', amount: 4, unit: 'cloves' },
      { name: 'Ginger', amount: 1, unit: 'tablespoon' },
      { name: 'Scotch bonnet peppers', amount: 2, unit: 'pieces' },
      { name: 'Onion', amount: 1, unit: 'large' },
      { name: 'Tomatoes', amount: 2, unit: 'large' },
      { name: 'Vegetable oil', amount: 3, unit: 'tablespoons' },
      { name: 'Salt', amount: 1, unit: 'teaspoon' },
      { name: 'Black pepper', amount: 1, unit: 'teaspoon' },
      { name: 'Lemon juice', amount: 2, unit: 'tablespoons' }
    ],
    instructions: [
      { stepNumber: 1, description: 'Prepare the Banku: In a large pot, mix the fermented corn dough and cassava dough with water. Stir until smooth.' },
      { stepNumber: 2, description: 'Cook the Banku mixture over medium heat, stirring continuously with a wooden spoon, until it thickens into a smooth, stretchy dough (about 30-40 minutes). Add salt to taste.' },
      { stepNumber: 3, description: 'Shape the Banku into balls or serve as is. Set aside and keep warm.' },
      { stepNumber: 4, description: 'Prepare the tilapia: Season the fish with salt, black pepper, minced garlic, ginger, and lemon juice. Let marinate for 15-20 minutes.' },
      { stepNumber: 5, description: 'Grill the tilapia on a preheated grill or grill pan for 5-7 minutes on each side, or until cooked through and slightly charred.' },
      { stepNumber: 6, description: 'Prepare the hot sauce: Heat vegetable oil in a pan. Sauté chopped onions, garlic, and ginger until fragrant.' },
      { stepNumber: 7, description: 'Add chopped tomatoes and Scotch bonnet peppers. Cook until the tomatoes break down and the sauce thickens (about 10 minutes). Season with salt to taste.' },
      { stepNumber: 8, description: 'Serve the Banku with grilled tilapia and hot sauce on the side. Enjoy hot.' }
    ],
    nutritionFacts: {
      protein: 35,
      carbs: 60,
      fat: 20,
      fiber: 5,
      sugar: 5,
      sodium: 700
    }
  }
];

const newAlgerianRecipes = [
  {
    title: 'Chakhchoukha',
    description: 'A hearty Algerian dish made with torn pieces of flatbread soaked in a spicy tomato-based sauce, often served with meat and vegetables.',
    cookingTime: 60,
    servings: 4,
    difficulty: 'MEDIUM',
    cuisineType: 'algerian',
    regionOfOrigin: 'Algeria',
    imageUrl: 'https://theodehlicious.com/wp-content/uploads/2023/11/Algerian-Chakhchoukha-II.jpg',
    calories: 400,
    type: 'MAIN',
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: false,
    isDairyFree: true,
    isNutFree: true,
    ingredients: [
      { name: 'Flatbread (rougag or markouk)', amount: 4, unit: 'pieces' },
      { name: 'Lamb or chicken', amount: 500, unit: 'grams' },
      { name: 'Tomatoes', amount: 4, unit: 'large' },
      { name: 'Onion', amount: 1, unit: 'medium' },
      { name: 'Garlic', amount: 3, unit: 'cloves' },
      { name: 'Chili pepper', amount: 1, unit: 'piece' },
      { name: 'Olive oil', amount: 3, unit: 'tablespoons' },
      { name: 'Spices (cumin, paprika)', amount: 1, unit: 'teaspoon each' },
      { name: 'Salt', amount: 1, unit: 'teaspoon', notes: 'to taste' }
    ],
    instructions: [
      { stepNumber: 1, description: 'Tear the flatbread into small pieces and set aside.' },
      { stepNumber: 2, description: 'In a pot, heat olive oil and sauté onions, garlic, and chili pepper.' },
      { stepNumber: 3, description: 'Add the meat and brown on all sides.' },
      { stepNumber: 4, description: 'Add chopped tomatoes, spices, and salt. Simmer for 30 minutes.' },
      { stepNumber: 5, description: 'Add the torn flatbread to the sauce and mix well.' },
      { stepNumber: 6, description: 'Serve hot as a main dish.' }
    ],
    nutritionFacts: {
      protein: 20,
      carbs: 50,
      fat: 15,
      fiber: 6,
      sugar: 5,
      sodium: 500
    }
  },
  {
    title: 'Rechta',
    description: 'A traditional Algerian pasta dish made with thin handmade noodles, served with a white sauce made from chicken or meat and vegetables.',
    cookingTime: 90,
    servings: 4,
    difficulty: 'MEDIUM',
    cuisineType: 'algerian',
    regionOfOrigin: 'Algeria',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/7/76/Rechta_tunisienne.jpg?20230519044949',
    calories: 500,
    type: 'MAIN',
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: false,
    isDairyFree: true,
    isNutFree: true,
    ingredients: [
      { name: 'Rechta noodles', amount: 2, unit: 'cups' },
      { name: 'Chicken or lamb', amount: 500, unit: 'grams' },
      { name: 'Onion', amount: 1, unit: 'medium' },
      { name: 'Garlic', amount: 3, unit: 'cloves' },
      { name: 'Chickpeas', amount: 1, unit: 'cup', notes: 'cooked' },
      { name: 'Turnip', amount: 1, unit: 'medium' },
      { name: 'Potatoes', amount: 2, unit: 'medium' },
      { name: 'Olive oil', amount: 3, unit: 'tablespoons' },
      { name: 'Spices (cinnamon, turmeric, bay leaves)', amount: 1, unit: 'teaspoon each' },
      { name: 'Salt', amount: 1, unit: 'teaspoon', notes: 'to taste' }
    ],
    instructions: [
      { stepNumber: 1, description: 'Cook the rechta noodles according to package instructions. Set aside.' },
      { stepNumber: 2, description: 'In a pot, heat olive oil and sauté onions and garlic.' },
      { stepNumber: 3, description: 'Add the meat and brown on all sides.' },
      { stepNumber: 4, description: 'Add chopped vegetables, chickpeas, spices, and enough water to cover. Simmer for 45 minutes.' },
      { stepNumber: 5, description: 'Serve the noodles topped with the meat and vegetable stew.' }
    ],
    nutritionFacts: {
      protein: 30,
      carbs: 70,
      fat: 15,
      fiber: 8,
      sugar: 5,
      sodium: 600
    }
  },
  {
    title: "Mhadjeb (Algerian Stuffed Pancakes)",
    description: 'A popular Algerian street food made with thin semolina pancakes stuffed with a flavorful mixture of onions, tomatoes, and spices.',
    cookingTime: 60,
    servings: 4,
    difficulty: 'MEDIUM',
    cuisineType: 'algerian',
    regionOfOrigin: 'Algeria',
    imageUrl: 'https://theafrikanstore.com/cdn/shop/articles/M_hadjeb-djoudjousemetauxfourneaux_720x@2x.webp?v=1693943087',
    calories: 300,
    type: 'SNACK',
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: false,
    isDairyFree: true,
    isNutFree: true,
    ingredients: [
      { name: 'Semolina', amount: 2, unit: 'cups' },
      { name: 'Water', amount: 1, unit: 'cup' },
      { name: 'Onions', amount: 2, unit: 'medium' },
      { name: 'Tomatoes', amount: 4, unit: 'large' },
      { name: 'Tomato paste', amount: 1, unit: 'tablespoon' },
      { name: 'Olive oil', amount: 3, unit: 'tablespoons' },
      { name: 'Spices (paprika, cumin)', amount: 1, unit: 'teaspoon each' },
      { name: 'Salt', amount: 1, unit: 'teaspoon', notes: 'to taste' }
    ],
    instructions: [
      { stepNumber: 1, description: 'Mix semolina and water to form a dough. Let it rest for 30 minutes.' },
      { stepNumber: 2, description: 'Sauté onions in olive oil until soft. Add tomatoes, tomato paste, and spices. Cook until thickened.' },
      { stepNumber: 3, description: 'Divide the dough into balls and roll out into thin circles.' },
      { stepNumber: 4, description: 'Place the filling on one half of the circle and fold over to seal.' },
      { stepNumber: 5, description: 'Cook on a hot griddle until golden brown on both sides.' },
      { stepNumber: 6, description: 'Serve warm as a snack or light meal.' }
    ],
    nutritionFacts: {
      protein: 8,
      carbs: 50,
      fat: 10,
      fiber: 4,
      sugar: 5,
      sodium: 400
    }
  },
  {
    title: 'Muamba de Galinha (Chicken Muamba)',
    description: 'A flavorful Angolan stew made with chicken, palm oil, okra, and garlic, often served with funge or rice.',
    cookingTime: 90,
    servings: 4,
    difficulty: 'MEDIUM',
    cuisineType: 'west-african',
    regionOfOrigin: 'Angola',
    imageUrl: 'https://jesseatsandtravels.com/wp-content/uploads/2018/03/africanpeanutstew.jpg',
    calories: 400,
    type: 'MAIN',
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: true,
    isDairyFree: true,
    isNutFree: true,
    ingredients: [
      { name: 'Chicken', amount: 1, unit: 'whole', notes: 'cut into pieces' },
      { name: 'Palm oil', amount: 4, unit: 'tablespoons' },
      { name: 'Okra', amount: 200, unit: 'grams' },
      { name: 'Garlic', amount: 4, unit: 'cloves' },
      { name: 'Onion', amount: 1, unit: 'large' },
      { name: 'Tomatoes', amount: 2, unit: 'large' },
      { name: 'Chili pepper', amount: 1, unit: 'piece' },
      { name: 'Water', amount: 2, unit: 'cups' },
      { name: 'Salt', amount: 1, unit: 'teaspoon', notes: 'to taste' }
    ],
    instructions: [
      { stepNumber: 1, description: 'Heat palm oil in a large pot. Add chopped onions and garlic, and sauté until fragrant.' },
      { stepNumber: 2, description: 'Add chicken pieces and brown on all sides.' },
      { stepNumber: 3, description: 'Add chopped tomatoes, chili pepper, and salt. Stir well.' },
      { stepNumber: 4, description: 'Add water and bring to a boil. Reduce heat and simmer for 30 minutes.' },
      { stepNumber: 5, description: 'Add okra and cook for another 20-30 minutes until the chicken is tender and the sauce thickens.' },
      { stepNumber: 6, description: 'Serve hot with funge or rice.' }
    ],
    nutritionFacts: {
      protein: 30,
      carbs: 15,
      fat: 25,
      fiber: 5,
      sugar: 4,
      sodium: 600
    }
  },
  {
    title: 'Calulu',
    description: 'A traditional Angolan dish made with dried fish or meat, tomatoes, okra, and eggplant, slow-cooked to perfection and served with funge or rice.',
    cookingTime: 120,
    servings: 4,
    difficulty: 'MEDIUM',
    cuisineType: 'west-african',
    regionOfOrigin: 'Angola',
    imageUrl: 'https://assets.tmecosys.com/image/upload/t_web767x639/img/recipe/ras/Assets/BB9056E2-2AAB-4748-936A-45B6E40075EC/Derivates/5eec90ab-dc43-4d91-8631-647514b9fd92.jpg',
    calories: 350,
    type: 'MAIN',
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: true,
    isDairyFree: true,
    isNutFree: true,
    ingredients: [
      { name: 'Dried fish or meat', amount: 500, unit: 'grams' },
      { name: 'Tomatoes', amount: 4, unit: 'large' },
      { name: 'Okra', amount: 200, unit: 'grams' },
      { name: 'Eggplant', amount: 1, unit: 'large' },
      { name: 'Palm oil', amount: 3, unit: 'tablespoons' },
      { name: 'Onion', amount: 1, unit: 'large' },
      { name: 'Garlic', amount: 4, unit: 'cloves' },
      { name: 'Chili pepper', amount: 1, unit: 'piece' },
      { name: 'Water', amount: 3, unit: 'cups' },
      { name: 'Salt', amount: 1, unit: 'teaspoon', notes: 'to taste' }
    ],
    instructions: [
      { stepNumber: 1, description: 'Soak the dried fish or meat in water for 30 minutes to rehydrate. Drain and set aside.' },
      { stepNumber: 2, description: 'Heat palm oil in a large pot. Sauté chopped onions and garlic until fragrant.' },
      { stepNumber: 3, description: 'Add the rehydrated fish or meat and brown lightly.' },
      { stepNumber: 4, description: 'Add chopped tomatoes, chili pepper, and salt. Stir well.' },
      { stepNumber: 5, description: 'Add water and bring to a boil. Reduce heat and simmer for 45 minutes.' },
      { stepNumber: 6, description: 'Add okra and eggplant. Cook for another 30 minutes until tender.' },
      { stepNumber: 7, description: 'Serve hot with funge or rice.' }
    ],
    nutritionFacts: {
      protein: 25,
      carbs: 20,
      fat: 18,
      fiber: 6,
      sugar: 5,
      sodium: 700
    }
  },
  {
    title: 'Mufete',
    description: 'A festive Angolan dish featuring grilled fish, beans, boiled plantains, and a spicy tomato sauce.',
    cookingTime: 60,
    servings: 4,
    difficulty: 'MEDIUM',
    cuisineType: 'west-african',
    regionOfOrigin: 'Angola',
    imageUrl: 'https://theafrikanstore.com/cdn/shop/articles/mufete-www.maxi.co.ao_1512x@2x.jpg?v=1696883963',
    calories: 450,
    type: 'MAIN',
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: true,
    isDairyFree: true,
    isNutFree: true,
    ingredients: [
      { name: 'Fresh fish (tilapia or mackerel)', amount: 4, unit: 'pieces' },
      { name: 'Beans', amount: 2, unit: 'cups', notes: 'cooked' },
      { name: 'Plantains', amount: 4, unit: 'pieces' },
      { name: 'Tomatoes', amount: 3, unit: 'large' },
      { name: 'Onion', amount: 1, unit: 'large' },
      { name: 'Chili pepper', amount: 1, unit: 'piece' },
      { name: 'Palm oil', amount: 3, unit: 'tablespoons' },
      { name: 'Salt', amount: 1, unit: 'teaspoon', notes: 'to taste' }
    ],
    instructions: [
      { stepNumber: 1, description: 'Grill the fish until cooked through. Set aside.' },
      { stepNumber: 2, description: 'Boil the plantains until tender. Set aside.' },
      { stepNumber: 3, description: 'In a pan, heat palm oil and sauté chopped onions and garlic.' },
      { stepNumber: 4, description: 'Add chopped tomatoes and chili pepper. Cook until the sauce thickens.' },
      { stepNumber: 5, description: 'Serve the grilled fish with boiled plantains, beans, and the spicy tomato sauce.' }
    ],
    nutritionFacts: {
      protein: 35,
      carbs: 50,
      fat: 15,
      fiber: 8,
      sugar: 10,
      sodium: 500
    }
  },
  {
    title: 'Kizaka (Cassava Leaves Stew)',
    description: 'A hearty Angolan stew made with pounded cassava leaves, palm oil, and often fish or meat, served with funge or rice.',
    cookingTime: 90,
    servings: 4,
    difficulty: 'MEDIUM',
    cuisineType: 'west-african',
    regionOfOrigin: 'Angola',
    imageUrl: 'https://cookingwithclaudy.com/wp-content/uploads/2023/11/20231103113714_IMG_6436.jpg',
    calories: 400,
    type: 'MAIN',
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: true,
    isDairyFree: true,
    isNutFree: true,
    ingredients: [
      { name: 'Cassava leaves', amount: 500, unit: 'grams' },
      { name: 'Palm oil', amount: 4, unit: 'tablespoons' },
      { name: 'Fish or meat', amount: 500, unit: 'grams' },
      { name: 'Garlic', amount: 4, unit: 'cloves' },
      { name: 'Onion', amount: 1, unit: 'large' },
      { name: 'Tomatoes', amount: 2, unit: 'large' },
      { name: 'Chili pepper', amount: 1, unit: 'piece' },
      { name: 'Water', amount: 3, unit: 'cups' },
      { name: 'Salt', amount: 1, unit: 'teaspoon', notes: 'to taste' }
    ],
    instructions: [
      { stepNumber: 1, description: 'Pound the cassava leaves until finely shredded. Set aside.' },
      { stepNumber: 2, description: 'Heat palm oil in a large pot. Sauté chopped onions and garlic until fragrant.' },
      { stepNumber: 3, description: 'Add the fish or meat and brown lightly.' },
      { stepNumber: 4, description: 'Add chopped tomatoes, chili pepper, and salt. Stir well.' },
      { stepNumber: 5, description: 'Add water and bring to a boil. Reduce heat and simmer for 30 minutes.' },
      { stepNumber: 6, description: 'Add the pounded cassava leaves and cook for another 30 minutes until tender.' },
      { stepNumber: 7, description: 'Serve hot with funge or rice.' }
    ],
    nutritionFacts: {
      protein: 20,
      carbs: 30,
      fat: 20,
      fiber: 8,
      sugar: 5,
      sodium: 600
    }
  },
  {
    title: 'Peanut Sponge Cake (Bolo de Ginguba)',
    description: 'A traditional Angolan dessert made with ground peanuts, flour, and eggs, resulting in a light and fluffy sponge cake with a nutty flavor.',
    cookingTime: 60,
    servings: 8,
    difficulty: 'MEDIUM',
    cuisineType: 'west-african',
    regionOfOrigin: 'Angola',
    imageUrl: 'https://assets.tmecosys.com/image/upload/t_web767x639/img/recipe/ras/Assets/F6620622-D0AC-48C6-906F-D6F9723B51AC/Derivates/29AE1111-6E6A-458D-903A-1ECC71DC7671.jpg',
    calories: 300,
    type: 'DESSERT',
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: false,
    isDairyFree: true,
    isNutFree: false,
    ingredients: [
      { name: 'All-purpose flour', amount: 2, unit: 'cups' },
      { name: 'Ground peanuts', amount: 1, unit: 'cup' },
      { name: 'Sugar', amount: 1, unit: 'cup' },
      { name: 'Eggs', amount: 4, unit: 'large' },
      { name: 'Baking powder', amount: 2, unit: 'teaspoons' },
      { name: 'Milk', amount: 1, unit: 'cup' },
      { name: 'Vegetable oil', amount: 1/2, unit: 'cup' },
      { name: 'Salt', amount: 1/2, unit: 'teaspoon' },
      { name: 'Vanilla extract', amount: 1, unit: 'teaspoon' }
    ],
    instructions: [
      { stepNumber: 1, description: 'Preheat the oven to 350°F (175°C). Grease and flour a cake pan.' },
      { stepNumber: 2, description: 'In a large bowl, whisk together the flour, ground peanuts, baking powder, and salt. Set aside.' },
      { stepNumber: 3, description: 'In a separate bowl, beat the eggs and sugar together until light and fluffy.' },
      { stepNumber: 4, description: 'Add the milk, vegetable oil, and vanilla extract to the egg mixture. Mix well.' },
      { stepNumber: 5, description: 'Gradually add the dry ingredients to the wet ingredients, mixing until just combined.' },
      { stepNumber: 6, description: 'Pour the batter into the prepared cake pan and smooth the top.' },
      { stepNumber: 7, description: 'Bake for 40-45 minutes, or until a toothpick inserted into the center comes out clean.' },
      { stepNumber: 8, description: 'Allow the cake to cool in the pan for 10 minutes, then transfer to a wire rack to cool completely.' },
      { stepNumber: 9, description: 'Serve as a dessert or snack, optionally garnished with crushed peanuts or a dusting of powdered sugar.' }
    ],
    nutritionFacts: {
      protein: 8,
      carbs: 40,
      fat: 12,
      fiber: 2,
      sugar: 20,
      sodium: 200
    }
  }
];

export const recipes = [...existingRecipes, ...newAlgerianRecipes]; 