// Sample recipe data
export const recipes = [
  {
    title: 'Quinoa Buddha Bowl',
    description: 'A nourishing bowl packed with protein-rich quinoa, roasted vegetables, and tahini dressing.',
    cookingTime: 30,
    servings: 2,
    difficulty: 'EASY',
    cuisineType: 'international',
    regionOfOrigin: 'Global',
    imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c',
    calories: 450,
    type: 'LUNCH',
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    isDairyFree: true,
    isNutFree: false,
    ingredients: [
      { name: 'Quinoa', amount: 1, unit: 'cup' },
      { name: 'Sweet Potato', amount: 1, unit: 'medium', notes: 'cubed' },
      { name: 'Chickpeas', amount: 1, unit: 'can', notes: 'drained and rinsed' },
      { name: 'Kale', amount: 2, unit: 'cups', notes: 'chopped' },
      { name: 'Tahini', amount: 2, unit: 'tablespoons' },
    ],
    instructions: [
      { stepNumber: 1, description: 'Cook quinoa according to package instructions.' },
      { stepNumber: 2, description: 'Roast sweet potato cubes at 400°F for 20 minutes.' },
      { stepNumber: 3, description: 'Massage kale with olive oil and season.' },
      { stepNumber: 4, description: 'Assemble bowls and drizzle with tahini dressing.' },
    ],
    nutritionFacts: {
      protein: 15,
      carbs: 65,
      fat: 12,
      fiber: 8,
      sugar: 6,
      sodium: 400,
    },
  },
  {
    title: 'Japanese Miso Soup',
    description: 'Traditional Japanese breakfast soup with tofu, wakame, and green onions.',
    cookingTime: 15,
    servings: 2,
    difficulty: 'EASY',
    cuisineType: 'japanese',
    regionOfOrigin: 'Japan',
    imageUrl: 'https://images.unsplash.com/photo-1547592166-23ac45744acd',
    calories: 120,
    type: 'BREAKFAST',
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    isDairyFree: true,
    isNutFree: true,
    ingredients: [
      { name: 'Dashi Stock', amount: 4, unit: 'cups' },
      { name: 'Miso Paste', amount: 3, unit: 'tablespoons' },
      { name: 'Tofu', amount: 200, unit: 'grams', notes: 'cubed' },
      { name: 'Wakame Seaweed', amount: 2, unit: 'tablespoons', notes: 'dried' },
      { name: 'Green Onions', amount: 2, unit: 'stalks', notes: 'chopped' },
    ],
    instructions: [
      { stepNumber: 1, description: 'Bring dashi stock to a simmer.' },
      { stepNumber: 2, description: 'Dissolve miso paste in a small amount of hot stock.' },
      { stepNumber: 3, description: 'Add tofu and wakame to the stock.' },
      { stepNumber: 4, description: 'Stir in miso mixture and garnish with green onions.' },
    ],
    nutritionFacts: {
      protein: 8,
      carbs: 12,
      fat: 4,
      fiber: 2,
      sugar: 1,
      sodium: 800,
    },
  },
  {
    title: 'Mediterranean Grilled Chicken',
    description: 'Herb-marinated chicken with Greek salad and tzatziki sauce.',
    cookingTime: 45,
    servings: 4,
    difficulty: 'MEDIUM',
    cuisineType: 'mediterranean',
    regionOfOrigin: 'Greece',
    imageUrl: 'https://images.unsplash.com/photo-1432139509613-5c4255815697',
    calories: 420,
    type: 'DINNER',
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: true,
    isDairyFree: false,
    isNutFree: true,
    ingredients: [
      { name: 'Chicken Breasts', amount: 4, unit: 'pieces' },
      { name: 'Greek Yogurt', amount: 1, unit: 'cup' },
      { name: 'Lemon', amount: 2, unit: 'whole' },
      { name: 'Garlic', amount: 4, unit: 'cloves' },
      { name: 'Oregano', amount: 2, unit: 'tablespoons' },
    ],
    instructions: [
      { stepNumber: 1, description: 'Marinate chicken in yogurt, lemon, garlic, and herbs.' },
      { stepNumber: 2, description: 'Grill chicken until cooked through.' },
      { stepNumber: 3, description: 'Prepare Greek salad and tzatziki sauce.' },
      { stepNumber: 4, description: 'Serve chicken with salad and sauce.' },
    ],
    nutritionFacts: {
      protein: 35,
      carbs: 12,
      fat: 28,
      fiber: 3,
      sugar: 4,
      sodium: 520,
    },
  },
  {
    title: 'Vegan Chocolate Energy Balls',
    description: 'No-bake energy balls made with dates, nuts, and cocoa.',
    cookingTime: 20,
    servings: 12,
    difficulty: 'EASY',
    cuisineType: 'international',
    regionOfOrigin: 'Global',
    imageUrl: 'https://images.unsplash.com/photo-1604467707321-70857c108c02',
    calories: 120,
    type: 'SNACK',
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    isDairyFree: true,
    isNutFree: false,
    ingredients: [
      { name: 'Medjool Dates', amount: 1, unit: 'cup', notes: 'pitted' },
      { name: 'Almonds', amount: 1, unit: 'cup' },
      { name: 'Cocoa Powder', amount: 2, unit: 'tablespoons' },
      { name: 'Chia Seeds', amount: 1, unit: 'tablespoon' },
      { name: 'Vanilla Extract', amount: 1, unit: 'teaspoon' },
    ],
    instructions: [
      { stepNumber: 1, description: 'Process dates and almonds in a food processor.' },
      { stepNumber: 2, description: 'Add cocoa powder, chia seeds, and vanilla.' },
      { stepNumber: 3, description: 'Roll mixture into balls.' },
      { stepNumber: 4, description: 'Refrigerate for 30 minutes before serving.' },
    ],
    nutritionFacts: {
      protein: 3,
      carbs: 18,
      fat: 7,
      fiber: 3,
      sugar: 12,
      sodium: 2,
    },
  },
  {
    title: 'Keto Cauliflower Mac and Cheese',
    description: 'Low-carb version of the classic comfort food using cauliflower.',
    cookingTime: 35,
    servings: 6,
    difficulty: 'MEDIUM',
    cuisineType: 'american',
    regionOfOrigin: 'United States',
    imageUrl: 'https://images.unsplash.com/photo-1543339494-b4cd4f7ba686',
    calories: 350,
    type: 'DINNER',
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: true,
    isDairyFree: false,
    isNutFree: true,
    ingredients: [
      { name: 'Cauliflower', amount: 2, unit: 'heads', notes: 'cut into florets' },
      { name: 'Heavy Cream', amount: 1, unit: 'cup' },
      { name: 'Cheddar Cheese', amount: 2, unit: 'cups', notes: 'shredded' },
      { name: 'Cream Cheese', amount: 4, unit: 'ounces' },
      { name: 'Garlic Powder', amount: 1, unit: 'teaspoon' },
    ],
    instructions: [
      { stepNumber: 1, description: 'Steam cauliflower until tender.' },
      { stepNumber: 2, description: 'Make cheese sauce with cream, cheeses, and seasonings.' },
      { stepNumber: 3, description: 'Combine cauliflower with cheese sauce.' },
      { stepNumber: 4, description: 'Bake until bubbly and golden.' },
    ],
    nutritionFacts: {
      protein: 18,
      carbs: 8,
      fat: 28,
      fiber: 3,
      sugar: 2,
      sodium: 480,
    },
  },
  {
    title: 'Spicy Pad Thai',
    description: 'Classic Thai stir-fried rice noodles with tofu, shrimp, and peanuts in a tangy-sweet sauce.',
    cookingTime: 30,
    servings: 4,
    difficulty: 'MEDIUM',
    cuisineType: 'thai',
    regionOfOrigin: 'Thailand',
    imageUrl: 'https://images.unsplash.com/photo-1559314809-0d155014e29e',
    calories: 450,
    type: 'DINNER',
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: true,
    isDairyFree: true,
    isNutFree: false,
    ingredients: [
      { name: 'Rice Noodles', amount: 8, unit: 'ounces' },
      { name: 'Tofu', amount: 8, unit: 'ounces', notes: 'firm, cubed' },
      { name: 'Shrimp', amount: 8, unit: 'ounces', notes: 'peeled and deveined' },
      { name: 'Bean Sprouts', amount: 2, unit: 'cups' },
      { name: 'Peanuts', amount: 0.5, unit: 'cup', notes: 'crushed' },
    ],
    instructions: [
      { stepNumber: 1, description: 'Soak rice noodles in warm water until soft.' },
      { stepNumber: 2, description: 'Stir-fry tofu and shrimp until cooked.' },
      { stepNumber: 3, description: 'Add noodles and sauce, toss until well-combined.' },
      { stepNumber: 4, description: 'Add bean sprouts and crushed peanuts.' },
    ],
    nutritionFacts: {
      protein: 25,
      carbs: 58,
      fat: 15,
      fiber: 4,
      sugar: 8,
      sodium: 850,
    },
  },
  {
    title: 'Butter Chicken',
    description: 'Creamy, aromatic Indian curry with tender chicken pieces in a rich tomato-based sauce.',
    cookingTime: 45,
    servings: 6,
    difficulty: 'MEDIUM',
    cuisineType: 'indian',
    regionOfOrigin: 'India',
    imageUrl: 'https://images.unsplash.com/photo-1588166524941-3bf61a9c41db',
    calories: 550,
    type: 'DINNER',
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: true,
    isDairyFree: false,
    isNutFree: true,
    ingredients: [
      { name: 'Chicken Thighs', amount: 2, unit: 'pounds', notes: 'boneless' },
      { name: 'Yogurt', amount: 1, unit: 'cup' },
      { name: 'Tomato Sauce', amount: 2, unit: 'cups' },
      { name: 'Heavy Cream', amount: 1, unit: 'cup' },
      { name: 'Garam Masala', amount: 2, unit: 'tablespoons' },
    ],
    instructions: [
      { stepNumber: 1, description: 'Marinate chicken in yogurt and spices.' },
      { stepNumber: 2, description: 'Cook chicken until golden brown.' },
      { stepNumber: 3, description: 'Simmer in tomato sauce until tender.' },
      { stepNumber: 4, description: 'Finish with cream and garnish.' },
    ],
    nutritionFacts: {
      protein: 32,
      carbs: 12,
      fat: 38,
      fiber: 2,
      sugar: 6,
      sodium: 720,
    },
  },
  {
    title: 'Sushi Roll Platter',
    description: 'Assorted fresh sushi rolls including California, Spicy Tuna, and Vegetable rolls.',
    cookingTime: 60,
    servings: 4,
    difficulty: 'HARD',
    cuisineType: 'japanese',
    regionOfOrigin: 'Japan',
    imageUrl: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c',
    calories: 400,
    type: 'DINNER',
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: false,
    isDairyFree: true,
    isNutFree: true,
    ingredients: [
      { name: 'Sushi Rice', amount: 2, unit: 'cups' },
      { name: 'Nori Sheets', amount: 6, unit: 'sheets' },
      { name: 'Tuna', amount: 8, unit: 'ounces', notes: 'sashimi grade' },
      { name: 'Cucumber', amount: 1, unit: 'whole' },
      { name: 'Avocado', amount: 2, unit: 'whole' },
    ],
    instructions: [
      { stepNumber: 1, description: 'Cook and season sushi rice.' },
      { stepNumber: 2, description: 'Prepare fillings and cut into strips.' },
      { stepNumber: 3, description: 'Roll sushi using bamboo mat.' },
      { stepNumber: 4, description: 'Slice rolls and arrange on platter.' },
    ],
    nutritionFacts: {
      protein: 18,
      carbs: 45,
      fat: 12,
      fiber: 4,
      sugar: 2,
      sodium: 380,
    },
  },
  {
    title: 'Vegetable Stir-Fry',
    description: 'Colorful mix of fresh vegetables in a savory sauce with tofu.',
    cookingTime: 25,
    servings: 4,
    difficulty: 'EASY',
    cuisineType: 'chinese',
    regionOfOrigin: 'China',
    imageUrl: 'https://images.unsplash.com/photo-1512058564366-18510be2db19',
    calories: 300,
    type: 'DINNER',
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    isDairyFree: true,
    isNutFree: true,
    ingredients: [
      { name: 'Mixed Vegetables', amount: 6, unit: 'cups' },
      { name: 'Tofu', amount: 14, unit: 'ounces', notes: 'firm' },
      { name: 'Soy Sauce', amount: 3, unit: 'tablespoons' },
      { name: 'Ginger', amount: 1, unit: 'tablespoon', notes: 'minced' },
      { name: 'Garlic', amount: 3, unit: 'cloves', notes: 'minced' },
    ],
    instructions: [
      { stepNumber: 1, description: 'Press and cube tofu.' },
      { stepNumber: 2, description: 'Stir-fry vegetables until crisp-tender.' },
      { stepNumber: 3, description: 'Add tofu and sauce.' },
      { stepNumber: 4, description: 'Cook until heated through.' },
    ],
    nutritionFacts: {
      protein: 15,
      carbs: 25,
      fat: 12,
      fiber: 6,
      sugar: 8,
      sodium: 600,
    },
  },
  {
    title: 'Greek Salad',
    description: 'Fresh Mediterranean salad with tomatoes, cucumbers, olives, and feta cheese.',
    cookingTime: 15,
    servings: 4,
    difficulty: 'EASY',
    cuisineType: 'mediterranean',
    regionOfOrigin: 'Greece',
    imageUrl: 'https://images.unsplash.com/photo-1522664074669-24ccf2f1a8f9',
    calories: 250,
    type: 'LUNCH',
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: true,
    isDairyFree: false,
    isNutFree: true,
    ingredients: [
      { name: 'Tomatoes', amount: 4, unit: 'whole' },
      { name: 'Cucumber', amount: 1, unit: 'large' },
      { name: 'Red Onion', amount: 1, unit: 'medium' },
      { name: 'Feta Cheese', amount: 200, unit: 'grams' },
      { name: 'Kalamata Olives', amount: 1, unit: 'cup' },
    ],
    instructions: [
      { stepNumber: 1, description: 'Chop vegetables into chunks.' },
      { stepNumber: 2, description: 'Combine in a large bowl.' },
      { stepNumber: 3, description: 'Add feta and olives.' },
      { stepNumber: 4, description: 'Dress with olive oil and oregano.' },
    ],
    nutritionFacts: {
      protein: 8,
      carbs: 12,
      fat: 20,
      fiber: 4,
      sugar: 6,
      sodium: 580,
    },
  },
  {
    title: 'Traditional French Croissants',
    description: 'Flaky, buttery French pastries made from laminated dough.',
    cookingTime: 180,
    servings: 8,
    difficulty: 'HARD',
    cuisineType: 'french',
    regionOfOrigin: 'France',
    imageUrl: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a',
    calories: 280,
    type: 'BREAKFAST',
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: false,
    isDairyFree: false,
    isNutFree: true,
    ingredients: [
      { name: 'All-Purpose Flour', amount: 4, unit: 'cups' },
      { name: 'Butter', amount: 1.5, unit: 'cups', notes: 'cold, for laminating' },
      { name: 'Active Dry Yeast', amount: 2.25, unit: 'teaspoons' },
      { name: 'Milk', amount: 1, unit: 'cup', notes: 'warm' },
      { name: 'Sugar', amount: 2, unit: 'tablespoons' },
    ],
    instructions: [
      { stepNumber: 1, description: 'Make enriched dough and chill.' },
      { stepNumber: 2, description: 'Laminate dough with butter through multiple folds.' },
      { stepNumber: 3, description: 'Shape croissants and proof.' },
      { stepNumber: 4, description: 'Bake until golden brown.' },
    ],
    nutritionFacts: {
      protein: 5,
      carbs: 28,
      fat: 18,
      fiber: 1,
      sugar: 3,
      sodium: 220,
    },
  },
  {
    title: 'Korean Bibimbap',
    description: 'A colorful rice bowl topped with vegetables, meat, and gochujang sauce.',
    cookingTime: 45,
    servings: 4,
    difficulty: 'MEDIUM',
    cuisineType: 'korean',
    regionOfOrigin: 'Korea',
    imageUrl: 'https://images.unsplash.com/photo-1553163147-622ab57be1c7',
    calories: 480,
    type: 'LUNCH',
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: true,
    isDairyFree: true,
    isNutFree: true,
    ingredients: [
      { name: 'Rice', amount: 2, unit: 'cups' },
      { name: 'Ground Beef', amount: 0.5, unit: 'pound' },
      { name: 'Spinach', amount: 2, unit: 'cups' },
      { name: 'Carrots', amount: 2, unit: 'medium' },
      { name: 'Gochujang', amount: 3, unit: 'tablespoons' },
    ],
    instructions: [
      { stepNumber: 1, description: 'Cook rice and prepare vegetables.' },
      { stepNumber: 2, description: 'Season and cook ground beef.' },
      { stepNumber: 3, description: 'Arrange ingredients in bowls.' },
      { stepNumber: 4, description: 'Top with fried egg and gochujang sauce.' },
    ],
    nutritionFacts: {
      protein: 22,
      carbs: 65,
      fat: 16,
      fiber: 4,
      sugar: 3,
      sodium: 680,
    },
  },
  {
    title: 'Moroccan Tagine',
    description: 'Slow-cooked aromatic stew with vegetables, preserved lemons, and olives.',
    cookingTime: 120,
    servings: 6,
    difficulty: 'MEDIUM',
    cuisineType: 'moroccan',
    regionOfOrigin: 'Morocco',
    imageUrl: 'https://images.unsplash.com/photo-1547595628-c61a29f496f0',
    calories: 380,
    type: 'DINNER',
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    isDairyFree: true,
    isNutFree: true,
    ingredients: [
      { name: 'Chickpeas', amount: 2, unit: 'cans' },
      { name: 'Sweet Potatoes', amount: 2, unit: 'large' },
      { name: 'Preserved Lemon', amount: 1, unit: 'whole' },
      { name: 'Green Olives', amount: 1, unit: 'cup' },
      { name: 'Ras el Hanout', amount: 2, unit: 'tablespoons' },
    ],
    instructions: [
      { stepNumber: 1, description: 'Layer vegetables in tagine.' },
      { stepNumber: 2, description: 'Add spices and preserved lemon.' },
      { stepNumber: 3, description: 'Slow cook until tender.' },
      { stepNumber: 4, description: 'Garnish with olives and herbs.' },
    ],
    nutritionFacts: {
      protein: 12,
      carbs: 45,
      fat: 14,
      fiber: 11,
      sugar: 8,
      sodium: 520,
    },
  },
  {
    title: 'Vietnamese Pho',
    description: 'Traditional Vietnamese noodle soup with aromatic broth and herbs.',
    cookingTime: 180,
    servings: 6,
    difficulty: 'HARD',
    cuisineType: 'vietnamese',
    regionOfOrigin: 'Vietnam',
    imageUrl: 'https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43',
    calories: 320,
    type: 'LUNCH',
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: true,
    isDairyFree: true,
    isNutFree: true,
    ingredients: [
      { name: 'Beef Bones', amount: 5, unit: 'pounds', notes: 'for broth' },
      { name: 'Rice Noodles', amount: 1, unit: 'pound' },
      { name: 'Star Anise', amount: 3, unit: 'whole' },
      { name: 'Ginger', amount: 4, unit: 'inches' },
      { name: 'Bean Sprouts', amount: 2, unit: 'cups' },
    ],
    instructions: [
      { stepNumber: 1, description: 'Simmer bones and spices for broth.' },
      { stepNumber: 2, description: 'Prepare noodles and garnishes.' },
      { stepNumber: 3, description: 'Strain and season broth.' },
      { stepNumber: 4, description: 'Assemble bowls with noodles and toppings.' },
    ],
    nutritionFacts: {
      protein: 24,
      carbs: 42,
      fat: 8,
      fiber: 2,
      sugar: 3,
      sodium: 890,
    },
  },
  {
    title: 'Mexican Chilaquiles',
    description: 'Crispy tortilla chips simmered in salsa verde with eggs and cheese.',
    cookingTime: 30,
    servings: 4,
    difficulty: 'EASY',
    cuisineType: 'mexican',
    regionOfOrigin: 'Mexico',
    imageUrl: 'https://images.unsplash.com/photo-1599974579688-8dbdd335c77f',
    calories: 420,
    type: 'BREAKFAST',
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: true,
    isDairyFree: false,
    isNutFree: true,
    ingredients: [
      { name: 'Corn Tortillas', amount: 12, unit: 'pieces' },
      { name: 'Salsa Verde', amount: 2, unit: 'cups' },
      { name: 'Eggs', amount: 4, unit: 'large' },
      { name: 'Queso Fresco', amount: 1, unit: 'cup' },
      { name: 'Cilantro', amount: 0.5, unit: 'cup' },
    ],
    instructions: [
      { stepNumber: 1, description: 'Cut and fry tortillas until crispy.' },
      { stepNumber: 2, description: 'Simmer chips in warm salsa verde.' },
      { stepNumber: 3, description: 'Top with fried eggs.' },
      { stepNumber: 4, description: 'Garnish with cheese and cilantro.' },
    ],
    nutritionFacts: {
      protein: 18,
      carbs: 48,
      fat: 22,
      fiber: 6,
      sugar: 4,
      sodium: 680,
    },
  },
  {
    title: 'Spanish Paella',
    description: 'Traditional Spanish rice dish with saffron, seafood, and vegetables.',
    cookingTime: 60,
    servings: 6,
    difficulty: 'HARD',
    cuisineType: 'spanish',
    regionOfOrigin: 'Spain',
    imageUrl: 'https://images.unsplash.com/photo-1534080564583-6be75777b70a',
    calories: 550,
    type: 'DINNER',
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: true,
    isDairyFree: true,
    isNutFree: true,
    ingredients: [
      { name: 'Bomba Rice', amount: 2, unit: 'cups' },
      { name: 'Mixed Seafood', amount: 1, unit: 'pound' },
      { name: 'Saffron', amount: 1, unit: 'pinch' },
      { name: 'Bell Peppers', amount: 2, unit: 'whole' },
      { name: 'Tomatoes', amount: 2, unit: 'whole' },
    ],
    instructions: [
      { stepNumber: 1, description: 'Toast rice with saffron.' },
      { stepNumber: 2, description: 'Add vegetables and broth.' },
      { stepNumber: 3, description: 'Add seafood and cook until done.' },
      { stepNumber: 4, description: 'Create socarrat (crispy bottom).' },
    ],
    nutritionFacts: {
      protein: 28,
      carbs: 65,
      fat: 12,
      fiber: 4,
      sugar: 5,
      sodium: 720,
    },
  },
  {
    title: 'Vegan Ramen',
    description: 'Plant-based version of the classic Japanese noodle soup.',
    cookingTime: 90,
    servings: 4,
    difficulty: 'MEDIUM',
    cuisineType: 'japanese',
    regionOfOrigin: 'Japan',
    imageUrl: 'https://images.unsplash.com/photo-1557872943-16a5ac26437e',
    calories: 380,
    type: 'LUNCH',
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: false,
    isDairyFree: true,
    isNutFree: true,
    ingredients: [
      { name: 'Ramen Noodles', amount: 4, unit: 'portions' },
      { name: 'Mushrooms', amount: 8, unit: 'ounces' },
      { name: 'Kombu', amount: 2, unit: 'pieces' },
      { name: 'Miso Paste', amount: 4, unit: 'tablespoons' },
      { name: 'Corn', amount: 1, unit: 'cup' },
    ],
    instructions: [
      { stepNumber: 1, description: 'Make mushroom and kombu broth.' },
      { stepNumber: 2, description: 'Prepare toppings and noodles.' },
      { stepNumber: 3, description: 'Season broth with miso.' },
      { stepNumber: 4, description: 'Assemble bowls with noodles and toppings.' },
    ],
    nutritionFacts: {
      protein: 14,
      carbs: 68,
      fat: 6,
      fiber: 8,
      sugar: 4,
      sodium: 890,
    },
  },
  {
    title: 'Lebanese Fattoush',
    description: 'Middle Eastern bread salad with sumac and pomegranate molasses.',
    cookingTime: 20,
    servings: 4,
    difficulty: 'EASY',
    cuisineType: 'middle-eastern',
    regionOfOrigin: 'Lebanon',
    imageUrl: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe',
    calories: 280,
    type: 'LUNCH',
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: false,
    isDairyFree: true,
    isNutFree: true,
    ingredients: [
      { name: 'Pita Bread', amount: 2, unit: 'pieces' },
      { name: 'Romaine Lettuce', amount: 1, unit: 'head' },
      { name: 'Sumac', amount: 2, unit: 'tablespoons' },
      { name: 'Pomegranate Molasses', amount: 2, unit: 'tablespoons' },
      { name: 'Mixed Herbs', amount: 1, unit: 'cup' },
    ],
    instructions: [
      { stepNumber: 1, description: 'Toast pita until crispy.' },
      { stepNumber: 2, description: 'Chop vegetables and herbs.' },
      { stepNumber: 3, description: 'Make sumac dressing.' },
      { stepNumber: 4, description: 'Toss all ingredients together.' },
    ],
    nutritionFacts: {
      protein: 6,
      carbs: 42,
      fat: 12,
      fiber: 6,
      sugar: 8,
      sodium: 380,
    },
  },
  {
    title: 'Brazilian Açaí Bowl',
    description: 'Refreshing breakfast bowl with açaí, fruits, and granola.',
    cookingTime: 15,
    servings: 2,
    difficulty: 'EASY',
    cuisineType: 'brazilian',
    regionOfOrigin: 'Brazil',
    imageUrl: 'https://images.unsplash.com/photo-1590301157890-4810ed352733',
    calories: 320,
    type: 'BREAKFAST',
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    isDairyFree: true,
    isNutFree: false,
    ingredients: [
      { name: 'Açaí Puree', amount: 200, unit: 'grams' },
      { name: 'Banana', amount: 1, unit: 'whole' },
      { name: 'Mixed Berries', amount: 1, unit: 'cup' },
      { name: 'Granola', amount: 0.5, unit: 'cup' },
      { name: 'Honey', amount: 2, unit: 'tablespoons' },
    ],
    instructions: [
      { stepNumber: 1, description: 'Blend açaí with banana.' },
      { stepNumber: 2, description: 'Pour into bowls.' },
      { stepNumber: 3, description: 'Top with fresh fruits.' },
      { stepNumber: 4, description: 'Add granola and drizzle honey.' },
    ],
    nutritionFacts: {
      protein: 8,
      carbs: 52,
      fat: 14,
      fiber: 12,
      sugar: 28,
      sodium: 45,
    },
  }
]; 