// Define Region data for seeding
// prisma/seed-data/regions.ts
export const regions = [
  // Continents
  { name: 'Africa', type: 'CONTINENT' },
  { name: 'Asia', type: 'CONTINENT' },
  { name: 'Europe', type: 'CONTINENT' },
  { name: 'North America', type: 'CONTINENT' },
  { name: 'South America', type: 'CONTINENT' },
  { name: 'Oceania', type: 'CONTINENT' },
  { name: 'Antarctica', type: 'CONTINENT' },

  // --- Africa ---
  // Sub-regions
  { name: 'Northern Africa', type: 'SUB_REGION', continent: 'Africa' },
  { name: 'Western Africa', type: 'SUB_REGION', continent: 'Africa' },
  { name: 'Eastern Africa', type: 'SUB_REGION', continent: 'Africa' },
  { name: 'Central Africa', type: 'SUB_REGION', continent: 'Africa' },
  { name: 'Southern Africa', type: 'SUB_REGION', continent: 'Africa' },
  // Countries
  { name: 'Algeria', type: 'COUNTRY', continent: 'Africa', parentName: 'Northern Africa' },
  { name: 'Angola', type: 'COUNTRY', continent: 'Africa', parentName: 'Central Africa' },
  { name: 'Benin', type: 'COUNTRY', continent: 'Africa', parentName: 'Western Africa' },
  { name: 'Botswana', type: 'COUNTRY', continent: 'Africa', parentName: 'Southern Africa' },
  { name: 'Burkina Faso', type: 'COUNTRY', continent: 'Africa', parentName: 'Western Africa' },
  { name: 'Burundi', type: 'COUNTRY', continent: 'Africa', parentName: 'Eastern Africa' },
  { name: 'Cabo Verde', type: 'COUNTRY', continent: 'Africa', parentName: 'Western Africa' },
  { name: 'Cameroon', type: 'COUNTRY', continent: 'Africa', parentName: 'Central Africa' },
  { name: 'Central African Republic', type: 'COUNTRY', continent: 'Africa', parentName: 'Central Africa' },
  { name: 'Chad', type: 'COUNTRY', continent: 'Africa', parentName: 'Central Africa' },
  { name: 'Comoros', type: 'COUNTRY', continent: 'Africa', parentName: 'Eastern Africa' },
  { name: 'Congo, Democratic Republic of the', type: 'COUNTRY', continent: 'Africa', parentName: 'Central Africa' },
  { name: 'Congo, Republic of the', type: 'COUNTRY', continent: 'Africa', parentName: 'Central Africa' },
  { name: 'Cote d\'Ivoire', type: 'COUNTRY', continent: 'Africa', parentName: 'Western Africa' },
  { name: 'Djibouti', type: 'COUNTRY', continent: 'Africa', parentName: 'Eastern Africa' },
  { name: 'Egypt', type: 'COUNTRY', continent: 'Africa', parentName: 'Northern Africa' },
  { name: 'Equatorial Guinea', type: 'COUNTRY', continent: 'Africa', parentName: 'Central Africa' },
  { name: 'Eritrea', type: 'COUNTRY', continent: 'Africa', parentName: 'Eastern Africa' },
  { name: 'Eswatini', type: 'COUNTRY', continent: 'Africa', parentName: 'Southern Africa' },
  { name: 'Ethiopia', type: 'COUNTRY', continent: 'Africa', parentName: 'Eastern Africa' },
  { name: 'Gabon', type: 'COUNTRY', continent: 'Africa', parentName: 'Central Africa' },
  { name: 'Gambia', type: 'COUNTRY', continent: 'Africa', parentName: 'Western Africa' },
  { name: 'Ghana', type: 'COUNTRY', continent: 'Africa', parentName: 'Western Africa' },
  { name: 'Guinea', type: 'COUNTRY', continent: 'Africa', parentName: 'Western Africa' },
  { name: 'Guinea-Bissau', type: 'COUNTRY', continent: 'Africa', parentName: 'Western Africa' },
  { name: 'Kenya', type: 'COUNTRY', continent: 'Africa', parentName: 'Eastern Africa' },
  { name: 'Lesotho', type: 'COUNTRY', continent: 'Africa', parentName: 'Southern Africa' },
  { name: 'Liberia', type: 'COUNTRY', continent: 'Africa', parentName: 'Western Africa' },
  { name: 'Libya', type: 'COUNTRY', continent: 'Africa', parentName: 'Northern Africa' },
  { name: 'Madagascar', type: 'COUNTRY', continent: 'Africa', parentName: 'Eastern Africa' },
  { name: 'Malawi', type: 'COUNTRY', continent: 'Africa', parentName: 'Eastern Africa' },
  { name: 'Mali', type: 'COUNTRY', continent: 'Africa', parentName: 'Western Africa' },
  { name: 'Mauritania', type: 'COUNTRY', continent: 'Africa', parentName: 'Western Africa' },
  { name: 'Mauritius', type: 'COUNTRY', continent: 'Africa', parentName: 'Eastern Africa' },
  { name: 'Morocco', type: 'COUNTRY', continent: 'Africa', parentName: 'Northern Africa' },
  { name: 'Mozambique', type: 'COUNTRY', continent: 'Africa', parentName: 'Eastern Africa' },
  { name: 'Namibia', type: 'COUNTRY', continent: 'Africa', parentName: 'Southern Africa' },
  { name: 'Niger', type: 'COUNTRY', continent: 'Africa', parentName: 'Western Africa' },
  { name: 'Nigeria', type: 'COUNTRY', continent: 'Africa', parentName: 'Western Africa' },
  { name: 'Rwanda', type: 'COUNTRY', continent: 'Africa', parentName: 'Eastern Africa' },
  { name: 'Sao Tome and Principe', type: 'COUNTRY', continent: 'Africa', parentName: 'Central Africa' },
  { name: 'Senegal', type: 'COUNTRY', continent: 'Africa', parentName: 'Western Africa' },
  { name: 'Seychelles', type: 'COUNTRY', continent: 'Africa', parentName: 'Eastern Africa' },
  { name: 'Sierra Leone', type: 'COUNTRY', continent: 'Africa', parentName: 'Western Africa' },
  { name: 'Somalia', type: 'COUNTRY', continent: 'Africa', parentName: 'Eastern Africa' },
  { name: 'South Africa', type: 'COUNTRY', continent: 'Africa', parentName: 'Southern Africa' },
  { name: 'South Sudan', type: 'COUNTRY', continent: 'Africa', parentName: 'Eastern Africa' },
  { name: 'Sudan', type: 'COUNTRY', continent: 'Africa', parentName: 'Northern Africa' },
  { name: 'Tanzania', type: 'COUNTRY', continent: 'Africa', parentName: 'Eastern Africa' },
  { name: 'Togo', type: 'COUNTRY', continent: 'Africa', parentName: 'Western Africa' },
  { name: 'Tunisia', type: 'COUNTRY', continent: 'Africa', parentName: 'Northern Africa' },
  { name: 'Uganda', type: 'COUNTRY', continent: 'Africa', parentName: 'Eastern Africa' },
  { name: 'Zambia', type: 'COUNTRY', continent: 'Africa', parentName: 'Eastern Africa' }, // Sometimes Southern
  { name: 'Zimbabwe', type: 'COUNTRY', continent: 'Africa', parentName: 'Eastern Africa' }, // Sometimes Southern

  // --- Asia ---
  // Sub-regions
  { name: 'Western Asia', type: 'SUB_REGION', continent: 'Asia' }, // (includes Middle East)
  { name: 'Central Asia', type: 'SUB_REGION', continent: 'Asia' },
  { name: 'South Asia', type: 'SUB_REGION', continent: 'Asia' },
  { name: 'East Asia', type: 'SUB_REGION', continent: 'Asia' },
  { name: 'Southeast Asia', type: 'SUB_REGION', continent: 'Asia' },
  // Countries
  { name: 'Afghanistan', type: 'COUNTRY', continent: 'Asia', parentName: 'South Asia' },
  { name: 'Armenia', type: 'COUNTRY', continent: 'Asia', parentName: 'Western Asia' },
  { name: 'Azerbaijan', type: 'COUNTRY', continent: 'Asia', parentName: 'Western Asia' },
  { name: 'Bahrain', type: 'COUNTRY', continent: 'Asia', parentName: 'Western Asia' },
  { name: 'Bangladesh', type: 'COUNTRY', continent: 'Asia', parentName: 'South Asia' },
  { name: 'Bhutan', type: 'COUNTRY', continent: 'Asia', parentName: 'South Asia' },
  { name: 'Brunei', type: 'COUNTRY', continent: 'Asia', parentName: 'Southeast Asia' },
  { name: 'Cambodia', type: 'COUNTRY', continent: 'Asia', parentName: 'Southeast Asia' },
  { name: 'China', type: 'COUNTRY', continent: 'Asia', parentName: 'East Asia' },
  { name: 'Cyprus', type: 'COUNTRY', continent: 'Asia', parentName: 'Western Asia' },
  { name: 'Georgia', type: 'COUNTRY', continent: 'Asia', parentName: 'Western Asia' },
  { name: 'India', type: 'COUNTRY', continent: 'Asia', parentName: 'South Asia' },
  { name: 'Indonesia', type: 'COUNTRY', continent: 'Asia', parentName: 'Southeast Asia' },
  { name: 'Iran', type: 'COUNTRY', continent: 'Asia', parentName: 'South Asia' },
  { name: 'Iraq', type: 'COUNTRY', continent: 'Asia', parentName: 'Western Asia' },
  { name: 'Israel', type: 'COUNTRY', continent: 'Asia', parentName: 'Western Asia' },
  { name: 'Japan', type: 'COUNTRY', continent: 'Asia', parentName: 'East Asia' },
  { name: 'Jordan', type: 'COUNTRY', continent: 'Asia', parentName: 'Western Asia' },
  { name: 'Kazakhstan', type: 'COUNTRY', continent: 'Asia', parentName: 'Central Asia' },
  { name: 'Kuwait', type: 'COUNTRY', continent: 'Asia', parentName: 'Western Asia' },
  { name: 'Kyrgyzstan', type: 'COUNTRY', continent: 'Asia', parentName: 'Central Asia' },
  { name: 'Laos', type: 'COUNTRY', continent: 'Asia', parentName: 'Southeast Asia' },
  { name: 'Lebanon', type: 'COUNTRY', continent: 'Asia', parentName: 'Western Asia' },
  { name: 'Malaysia', type: 'COUNTRY', continent: 'Asia', parentName: 'Southeast Asia' },
  { name: 'Maldives', type: 'COUNTRY', continent: 'Asia', parentName: 'South Asia' },
  { name: 'Mongolia', type: 'COUNTRY', continent: 'Asia', parentName: 'East Asia' },
  { name: 'Myanmar', type: 'COUNTRY', continent: 'Asia', parentName: 'Southeast Asia' },
  { name: 'Nepal', type: 'COUNTRY', continent: 'Asia', parentName: 'South Asia' },
  { name: 'North Korea', type: 'COUNTRY', continent: 'Asia', parentName: 'East Asia' },
  { name: 'Oman', type: 'COUNTRY', continent: 'Asia', parentName: 'Western Asia' },
  { name: 'Pakistan', type: 'COUNTRY', continent: 'Asia', parentName: 'South Asia' },
  { name: 'Palestine', type: 'COUNTRY', continent: 'Asia', parentName: 'Western Asia' },
  { name: 'Philippines', type: 'COUNTRY', continent: 'Asia', parentName: 'Southeast Asia' },
  { name: 'Qatar', type: 'COUNTRY', continent: 'Asia', parentName: 'Western Asia' },
  { name: 'Saudi Arabia', type: 'COUNTRY', continent: 'Asia', parentName: 'Western Asia' },
  { name: 'Singapore', type: 'COUNTRY', continent: 'Asia', parentName: 'Southeast Asia' },
  { name: 'South Korea', type: 'COUNTRY', continent: 'Asia', parentName: 'East Asia' },
  { name: 'Sri Lanka', type: 'COUNTRY', continent: 'Asia', parentName: 'South Asia' },
  { name: 'Syria', type: 'COUNTRY', continent: 'Asia', parentName: 'Western Asia' },
  { name: 'Taiwan', type: 'COUNTRY', continent: 'Asia', parentName: 'East Asia' },
  { name: 'Tajikistan', type: 'COUNTRY', continent: 'Asia', parentName: 'Central Asia' },
  { name: 'Thailand', type: 'COUNTRY', continent: 'Asia', parentName: 'Southeast Asia' },
  { name: 'Timor-Leste', type: 'COUNTRY', continent: 'Asia', parentName: 'Southeast Asia' },
  { name: 'Turkey', type: 'COUNTRY', continent: 'Asia', parentName: 'Western Asia' }, // Transcontinental
  { name: 'Turkmenistan', type: 'COUNTRY', continent: 'Asia', parentName: 'Central Asia' },
  { name: 'United Arab Emirates', type: 'COUNTRY', continent: 'Asia', parentName: 'Western Asia' },
  { name: 'Uzbekistan', type: 'COUNTRY', continent: 'Asia', parentName: 'Central Asia' },
  { name: 'Vietnam', type: 'COUNTRY', continent: 'Asia', parentName: 'Southeast Asia' },
  { name: 'Yemen', type: 'COUNTRY', continent: 'Asia', parentName: 'Western Asia' },

  // --- Europe ---
  // Sub-regions
  { name: 'Northern Europe', type: 'SUB_REGION', continent: 'Europe' },
  { name: 'Western Europe', type: 'SUB_REGION', continent: 'Europe' },
  { name: 'Southern Europe', type: 'SUB_REGION', continent: 'Europe' },
  { name: 'Eastern Europe', type: 'SUB_REGION', continent: 'Europe' },
  { name: 'Southeastern Europe', type: 'SUB_REGION', continent: 'Europe' },
  // Countries
  { name: 'Albania', type: 'COUNTRY', continent: 'Europe', parentName: 'Southeastern Europe' },
  { name: 'Andorra', type: 'COUNTRY', continent: 'Europe', parentName: 'Southern Europe' },
  { name: 'Austria', type: 'COUNTRY', continent: 'Europe', parentName: 'Western Europe' },
  { name: 'Belarus', type: 'COUNTRY', continent: 'Europe', parentName: 'Eastern Europe' },
  { name: 'Belgium', type: 'COUNTRY', continent: 'Europe', parentName: 'Western Europe' },
  { name: 'Bosnia and Herzegovina', type: 'COUNTRY', continent: 'Europe', parentName: 'Southeastern Europe' },
  { name: 'Bulgaria', type: 'COUNTRY', continent: 'Europe', parentName: 'Southeastern Europe' },
  { name: 'Croatia', type: 'COUNTRY', continent: 'Europe', parentName: 'Southeastern Europe' },
  { name: 'Czech Republic', type: 'COUNTRY', continent: 'Europe', parentName: 'Eastern Europe' },
  { name: 'Denmark', type: 'COUNTRY', continent: 'Europe', parentName: 'Northern Europe' },
  { name: 'Estonia', type: 'COUNTRY', continent: 'Europe', parentName: 'Northern Europe' },
  { name: 'Finland', type: 'COUNTRY', continent: 'Europe', parentName: 'Northern Europe' },
  { name: 'France', type: 'COUNTRY', continent: 'Europe', parentName: 'Western Europe' },
  { name: 'Germany', type: 'COUNTRY', continent: 'Europe', parentName: 'Western Europe' },
  { name: 'Greece', type: 'COUNTRY', continent: 'Europe', parentName: 'Southeastern Europe' },
  { name: 'Hungary', type: 'COUNTRY', continent: 'Europe', parentName: 'Eastern Europe' },
  { name: 'Iceland', type: 'COUNTRY', continent: 'Europe', parentName: 'Northern Europe' },
  { name: 'Ireland', type: 'COUNTRY', continent: 'Europe', parentName: 'Northern Europe' },
  { name: 'Italy', type: 'COUNTRY', continent: 'Europe', parentName: 'Southern Europe' },
  { name: 'Latvia', type: 'COUNTRY', continent: 'Europe', parentName: 'Northern Europe' },
  { name: 'Liechtenstein', type: 'COUNTRY', continent: 'Europe', parentName: 'Western Europe' },
  { name: 'Lithuania', type: 'COUNTRY', continent: 'Europe', parentName: 'Northern Europe' },
  { name: 'Luxembourg', type: 'COUNTRY', continent: 'Europe', parentName: 'Western Europe' },
  { name: 'Malta', type: 'COUNTRY', continent: 'Europe', parentName: 'Southern Europe' },
  { name: 'Moldova', type: 'COUNTRY', continent: 'Europe', parentName: 'Eastern Europe' },
  { name: 'Monaco', type: 'COUNTRY', continent: 'Europe', parentName: 'Western Europe' },
  { name: 'Montenegro', type: 'COUNTRY', continent: 'Europe', parentName: 'Southeastern Europe' },
  { name: 'Netherlands', type: 'COUNTRY', continent: 'Europe', parentName: 'Western Europe' },
  { name: 'North Macedonia', type: 'COUNTRY', continent: 'Europe', parentName: 'Southeastern Europe' },
  { name: 'Norway', type: 'COUNTRY', continent: 'Europe', parentName: 'Northern Europe' },
  { name: 'Poland', type: 'COUNTRY', continent: 'Europe', parentName: 'Eastern Europe' },
  { name: 'Portugal', type: 'COUNTRY', continent: 'Europe', parentName: 'Southern Europe' },
  { name: 'Romania', type: 'COUNTRY', continent: 'Europe', parentName: 'Southeastern Europe' },
  { name: 'Russia', type: 'COUNTRY', continent: 'Europe', parentName: 'Eastern Europe' }, // Transcontinental
  { name: 'San Marino', type: 'COUNTRY', continent: 'Europe', parentName: 'Southern Europe' },
  { name: 'Serbia', type: 'COUNTRY', continent: 'Europe', parentName: 'Southeastern Europe' },
  { name: 'Slovakia', type: 'COUNTRY', continent: 'Europe', parentName: 'Eastern Europe' },
  { name: 'Slovenia', type: 'COUNTRY', continent: 'Europe', parentName: 'Southeastern Europe' },
  { name: 'Spain', type: 'COUNTRY', continent: 'Europe', parentName: 'Southern Europe' },
  { name: 'Sweden', type: 'COUNTRY', continent: 'Europe', parentName: 'Northern Europe' },
  { name: 'Switzerland', type: 'COUNTRY', continent: 'Europe', parentName: 'Western Europe' },
  { name: 'Ukraine', type: 'COUNTRY', continent: 'Europe', parentName: 'Eastern Europe' },
  { name: 'United Kingdom', type: 'COUNTRY', continent: 'Europe', parentName: 'Northern Europe' },
  { name: 'Vatican City', type: 'COUNTRY', continent: 'Europe', parentName: 'Southern Europe' },

  // --- North America ---
  // Sub-regions
  { name: 'Central America', type: 'SUB_REGION', continent: 'North America' },
  { name: 'Caribbean', type: 'SUB_REGION', continent: 'North America' },
  // Countries
  { name: 'Antigua and Barbuda', type: 'COUNTRY', continent: 'North America', parentName: 'Caribbean' },
  { name: 'Bahamas', type: 'COUNTRY', continent: 'North America', parentName: 'Caribbean' },
  { name: 'Barbados', type: 'COUNTRY', continent: 'North America', parentName: 'Caribbean' },
  { name: 'Belize', type: 'COUNTRY', continent: 'North America', parentName: 'Central America' },
  { name: 'Canada', type: 'COUNTRY', continent: 'North America' }, // No parent sub-region in this list
  { name: 'Costa Rica', type: 'COUNTRY', continent: 'North America', parentName: 'Central America' },
  { name: 'Cuba', type: 'COUNTRY', continent: 'North America', parentName: 'Caribbean' },
  { name: 'Dominica', type: 'COUNTRY', continent: 'North America', parentName: 'Caribbean' },
  { name: 'Dominican Republic', type: 'COUNTRY', continent: 'North America', parentName: 'Caribbean' },
  { name: 'El Salvador', type: 'COUNTRY', continent: 'North America', parentName: 'Central America' },
  { name: 'Grenada', type: 'COUNTRY', continent: 'North America', parentName: 'Caribbean' },
  { name: 'Guatemala', type: 'COUNTRY', continent: 'North America', parentName: 'Central America' },
  { name: 'Haiti', type: 'COUNTRY', continent: 'North America', parentName: 'Caribbean' },
  { name: 'Honduras', type: 'COUNTRY', continent: 'North America', parentName: 'Central America' },
  { name: 'Jamaica', type: 'COUNTRY', continent: 'North America', parentName: 'Caribbean' },
  { name: 'Mexico', type: 'COUNTRY', continent: 'North America', parentName: 'Central America' }, // Often considered N.America, but maps to user's C.America sub-region
  { name: 'Nicaragua', type: 'COUNTRY', continent: 'North America', parentName: 'Central America' },
  { name: 'Panama', type: 'COUNTRY', continent: 'North America', parentName: 'Central America' },
  { name: 'Puerto Rico', type: 'COUNTRY', continent: 'North America', parentName: 'Caribbean' }, // US Territory
  { name: 'Saint Kitts and Nevis', type: 'COUNTRY', continent: 'North America', parentName: 'Caribbean' },
  { name: 'Saint Lucia', type: 'COUNTRY', continent: 'North America', parentName: 'Caribbean' },
  { name: 'Saint Vincent and the Grenadines', type: 'COUNTRY', continent: 'North America', parentName: 'Caribbean' },
  { name: 'Trinidad and Tobago', type: 'COUNTRY', continent: 'North America', parentName: 'Caribbean' },
  { name: 'United States', type: 'COUNTRY', continent: 'North America' }, // No parent sub-region in this list

  // --- South America ---
  // Countries (No sub-regions defined by user, so no parentName needed)
  { name: 'Argentina', type: 'COUNTRY', continent: 'South America' },
  { name: 'Bolivia', type: 'COUNTRY', continent: 'South America' },
  { name: 'Brazil', type: 'COUNTRY', continent: 'South America' },
  { name: 'Chile', type: 'COUNTRY', continent: 'South America' },
  { name: 'Colombia', type: 'COUNTRY', continent: 'South America' },
  { name: 'Ecuador', type: 'COUNTRY', continent: 'South America' },
  { name: 'French Guiana', type: 'COUNTRY', continent: 'South America' }, 
  { name: 'Guyana', type: 'COUNTRY', continent: 'South America' },
  { name: 'Paraguay', type: 'COUNTRY', continent: 'South America' },
  { name: 'Peru', type: 'COUNTRY', continent: 'South America' },
  { name: 'Suriname', type: 'COUNTRY', continent: 'South America' },
  { name: 'Uruguay', type: 'COUNTRY', continent: 'South America' },
  { name: 'Venezuela', type: 'COUNTRY', continent: 'South America' },

  // --- Oceania ---
  // Sub-regions
  { name: 'Australasia', type: 'SUB_REGION', continent: 'Oceania' },
  { name: 'Melanesia', type: 'SUB_REGION', continent: 'Oceania' },
  { name: 'Micronesia', type: 'SUB_REGION', continent: 'Oceania' },
  { name: 'Polynesia', type: 'SUB_REGION', continent: 'Oceania' },
  // Countries
  { name: 'Australia', type: 'COUNTRY', continent: 'Oceania', parentName: 'Australasia' },
  { name: 'Fiji', type: 'COUNTRY', continent: 'Oceania', parentName: 'Melanesia' },
  { name: 'Kiribati', type: 'COUNTRY', continent: 'Oceania', parentName: 'Micronesia' },
  { name: 'Marshall Islands', type: 'COUNTRY', continent: 'Oceania', parentName: 'Micronesia' },
  { name: 'Micronesia, Federated States of', type: 'COUNTRY', continent: 'Oceania', parentName: 'Micronesia' },
  { name: 'Nauru', type: 'COUNTRY', continent: 'Oceania', parentName: 'Micronesia' },
  { name: 'New Zealand', type: 'COUNTRY', continent: 'Oceania', parentName: 'Australasia' },
  { name: 'Palau', type: 'COUNTRY', continent: 'Oceania', parentName: 'Micronesia' },
  { name: 'Papua New Guinea', type: 'COUNTRY', continent: 'Oceania', parentName: 'Melanesia' },
  { name: 'Samoa', type: 'COUNTRY', continent: 'Oceania', parentName: 'Polynesia' },
  { name: 'Solomon Islands', type: 'COUNTRY', continent: 'Oceania', parentName: 'Melanesia' },
  { name: 'Tonga', type: 'COUNTRY', continent: 'Oceania', parentName: 'Polynesia' },
  { name: 'Tuvalu', type: 'COUNTRY', continent: 'Oceania', parentName: 'Polynesia' },
  { name: 'Vanuatu', type: 'COUNTRY', continent: 'Oceania', parentName: 'Melanesia' },
];